from __future__ import annotations

import shutil
from pathlib import Path

from docx import Document


DOC_PATH = Path(r"B:\Downloads\Graduation Project Documentation 2.docx")
BACKUP_PATH = DOC_PATH.with_name("Graduation Project Documentation 2.before-current-system-update.docx")


PARAGRAPH_UPDATES: dict[int, str] = {
    9: "S.A.G.A.: A Database-Native Narrative Intelligence System for Canonical Story Analysis, Retrieval, and Controlled Generation",
    47: "Our goal is to develop an intelligent storytelling system called S.A.G.A. (Story Analysis, Generation, and Archives) that analyzes existing books to understand characters, events, relationships, timelines, and visual state at a canonical level. The current system is built around SQLite-backed canonical storage, BookNLP-clean identity resolution, staged database-native analysis agents, a React and FastAPI dashboard runtime, decoder workflows for canon-aware story generation, and structured visual prompt generation for rendering. This work aims to move beyond prompt-only storytelling by building reusable canonical memory that supports consistent analysis, retrieval, visual continuity, and controlled narrative expansion.",
    136: "S.A.G.A. is an AI-driven narrative intelligence workspace designed to address these challenges by combining deep narrative analysis with database-native canonical memory. The system analyzes and structures story elements such as characters, events, relationships, timelines, states, and visual descriptors to create a persistent representation of a fictional world. Using this structured knowledge, the platform supports retrieval, review, controlled generation, and visual workflows while maintaining consistency and coherence within the story universe.",
    137: "To enhance downstream usefulness, S.A.G.A. connects narrative analysis to practical operator workflows. Canonical outputs can be reviewed through a local dashboard, used to generate decoder-driven story continuations and alternate paths, and transformed into scene-based or character-based visual prompts for rendering. By integrating analysis, persistence, inspection, generation, and visual continuity support within one framework, the system provides a coherent environment for studying and extending fictional worlds.",
    138: "Why S.A.G.A.?",
    141: 'The name S.A.G.A. stands for "Story Analysis, Generation, and Archives". It was chosen to represent the full lifecycle of the project: analyzing source narratives, preserving their canonical memory in a durable store, and using that memory to support controlled generation and visual workflows. The name also reflects the project\'s focus on long-form fiction, continuity, and reusable story intelligence rather than one-off prompt generation.',
    144: "The motivation behind S.A.G.A. is to develop a storytelling system that understands stories before generating or transforming new content. By analyzing existing narratives and modeling their structural components, the system can capture relationships between characters, events, settings, timelines, and visual state. This deeper narrative understanding enables more coherent downstream generation while preserving the integrity of the original narrative world.",
    145: "The platform is primarily intended for researchers, story analysts, book enthusiasts, and creators who want to inspect canon deeply before extending it. These users often need to review events, states, relationships, and visual continuity, then use that knowledge to explore sequels, prequels, divergence scenarios, or perspective-based narratives with stronger grounding.",
    146: "Finally, the project is motivated by the need to unify analysis and downstream usage. In many current workflows, story extraction, generation, and visual rendering are disconnected, which makes consistency difficult to maintain. By connecting canonical persistence, dashboard review, decoder workflows, and visual prompt generation, S.A.G.A. provides a more reliable foundation for long-form narrative intelligence.",
    152: "Furthermore, although multimodal generation technologies for text and image creation have advanced considerably, they are often implemented as separate systems with limited shared memory. This fragmentation leads to inefficient workflows, inconsistencies across generated outputs, and difficulties in preserving character identity, narrative continuity, and visual coherence across scenes.",
    154: "Therefore, there exists a critical need for an integrated AI-driven system capable of reverse-engineering existing narratives, extracting structured canonical knowledge, and leveraging this structure to support coherent analysis, retrieval, controlled generation, and visually grounded downstream workflows. Such a system should preserve narrative continuity, character consistency, event logic, and scene-aware visual state within one unified framework.",
    163: "The main goal of S.A.G.A. is to develop a database-native narrative intelligence system capable of analyzing stories, preserving canonical memory, and supporting canon-aware generation and visual workflows while maintaining consistency. The system analyzes books to extract narrative structure and durable story knowledge, including characters, locations, major events, relationships, timelines, stable traits, and scene-level state changes.",
    165: "The system builds upon this extracted knowledge by storing it in a canonical SQLite repository and exposing it through dashboard, retrieval, decoder, and visual services. In this way, narrative analysis is not treated as a disposable preprocessing step, but as the operational core that supports coherent story continuation, divergence planning, scene visualization, and long-term inspection.",
    168: "1. Narrative Knowledge Extraction",
    169: "- Develop a system capable of analyzing existing stories and extracting key narrative components, including characters, locations, major events, relationships, timelines, and scene-level world state.",
    170: "- Ensure accurate identification and normalization of story elements to support deep understanding of narrative structure and canon logic.",
    171: "2. Canonical Persistence and Identity Stability",
    172: "- Store extracted narrative knowledge in a durable SQLite-backed canonical repository instead of temporary file-based artifacts.",
    173: "- Establish stable BookNLP-clean identity bundles and alias resolution before deeper downstream analysis.",
    174: "3. Canon-Aware Story Generation",
    175: "- Support decoder workflows for pre-canon, mid-canon, post-canon, and alternate-universe generation modes.",
    176: "- Preserve narrative consistency while enabling grounded continuation, insertion, and divergence-based story exploration.",
    177: "4. Visual Prompt and Scene Generation Support",
    178: "- Generate structured character, object, location, and scene prompts from canonical memory to support downstream rendering workflows.",
    179: "- Maintain visual consistency using baseline traits and scene-specific visual state rather than isolated one-shot prompts.",
    180: "5. Dashboard Review and Operational Control",
    181: "- Provide a local dashboard for staging uploads, validating import plans, starting jobs, and inspecting analysis, decoder, and visual outputs.",
    182: "6. Reliability and Resumable Processing",
    183: "- Maintain logical continuity across persisted analysis, generated stories, visual prompts, and stored outputs.",
    184: "- Support stage-based execution, provider health visibility, and resumable job behavior for long-running analyses.",
    185: "7. Extensible Narrative Intelligence Platform",
    186: "- Combine analysis, retrieval, decoder generation, and visual rendering support within a unified local framework.",
    187: "- Provide an extensible architecture for future point-in-time querying, rewrite planning, causal reasoning, and richer canon services.",
    252: "In contrast, S.A.G.A. is designed as a database-native storytelling intelligence framework that prioritizes canonical extraction, durable persistence, operator review, controlled generation, and visual continuity support within a single system. Rather than depending on prompt-only generation, the platform builds reusable memory for characters, events, states, and timelines, then reuses that memory across dashboard inspection, decoder workflows, and visual prompt generation. This approach addresses key limitations of existing solutions and provides a more rigorous environment for long-form story analysis and extension.",
    257: "S.A.G.A. analyzes narrative content to identify key story elements, including characters, relationships, events, scenes, timelines, and visual state. This structured representation enables deeper understanding of fictional worlds and supports more coherent downstream generation and review.",
    261: "S.A.G.A. enables controlled narrative generation based on persisted story knowledge, allowing stories to be extended, adapted, and explored through grounded decoder workflows while maintaining continuity and narrative coherence.",
    265: "Our system analyzes scene segmentation, event causality, relationship changes, state transitions, and visual evidence, enabling structured story planning and more reliable long-form generation. This allows the system to maintain logical continuity when generating or extending narratives.",
    269: "Our system generates structured visual assets, including canonical character sheets and scene-aligned prompts, based on extracted character baselines and scene information. This ensures stronger consistency between textual descriptions and visual outputs across multiple scenes.",
    272: "By generating standardized character baselines and tracking scene-level visual changes, the system establishes persistent visual identities that can be reused across scene generation, maintaining continuity throughout the story.",
    277: "S.A.G.A. does not treat narration as the core downstream path. Instead, it focuses on high-trust canonical analysis, dashboard review, controlled text generation, and visual workflows that can later be extended to other modalities if needed.",
    280: "Text generation, canonical analysis, retrieval, and image creation are typically implemented as separate processes, requiring manual integration and often resulting in inconsistencies between analysis-time knowledge and generation-time outputs.",
    281: "S.A.G.A. combines database-native canonical memory, dashboard operations, decoder generation, and visual prompt generation within a unified framework, enabling a cohesive long-form storytelling workflow while preserving narrative consistency across textual and visual outputs.",
    284: "As illustrated in Table 2.1, S.A.G.A. provides stronger canonical extraction, operational persistence, and consistency control than prompt-driven storytelling tools.",
    398: "The theoretical analysis identified and prioritized the core requirements of the S.A.G.A. system and the subsequent mapping of narrative concepts to system functionality. Story structure processing and canonical persistence were determined to be the highest priorities because they provide the foundation for downstream retrieval, generation, and review tasks. Character modeling, event tracking, and relationship/state continuity were identified as the next most important components to ensure consistency and believable narrative development. These findings guided the architectural design of S.A.G.A. by establishing a structured hierarchy of system requirements aligned with the current database-native implementation.",
    402: "The survey results support the design of S.A.G.A. by confirming strong user demand for narrative understanding, interactive story modification, and visual storytelling support. Users value automatic extraction of story elements, the ability to generate sequels and alternative outcomes, and the inclusion of scene visualization to enhance engagement and comprehension. These findings validate the system's focus on canonical extraction, dashboard review, decoder workflows, and visual continuity rather than purely prompt-driven generation.",
    412: "Integration of canonical analysis, decoder workflows, and image-based scene generation",
    414: "As illustrated in Table 3.5, this systematic requirement analysis ensures that S.A.G.A. is not merely a text generator, but a narrative-intelligent platform grounded in storytelling theory, durable memory, and operational review.",
    440: "FR6. The system shall generate canon-aware narrative extensions and adaptations, including pre-canon, mid-canon, post-canon, and alternate-universe outputs grounded in persisted story memory.",
    441: "FR7. The system shall allow users to specify continuity anchors, divergence anchors, and other generation controls for decoder workflows.",
    442: "FR8. The system shall maintain narrative consistency across generated characters, events, relationships, timelines, and state transitions.",
    444: "Visual Prompting and Rendering",
    445: "FR9. The system shall derive scene-aware and entity-aware visual prompt records from persisted canonical memory.",
    446: "FR10. The system shall support one or more visual render workflows for character sheets, scenes, and other grounded visual assets.",
    447: "FR11. The system shall maintain visual consistency of characters and settings across generated scenes by reusing baselines and scene-level state.",
    448: "FR12. The system shall allow prompt versioning and configurable visual generation controls.",
    449: "Dashboard and Review",
    450: "FR13. The system shall provide a local dashboard for staging uploads, validating import plans, and monitoring analysis jobs.",
    451: "FR14. The system shall expose provider health, diagnostics, and runtime status for supported backends.",
    452: "FR15. The system shall allow users to inspect persisted books, scenes, entities, events, states, prompts, and generated stories.",
    453: "FR16. The system shall store generated stories, prompts, and render outputs together with metadata and verification details.",
    454: "Output and Interaction",
    455: "FR17. The system shall allow the user to preview structured analysis and generated outputs through the local dashboard.",
    456: "FR18. The system shall allow the user to retry failed jobs, rerun supported workflows, and safely cancel long-running tasks at supported boundaries.",
    457: "FR19. The system shall allow the user to export generated story text, EPUB outputs, and visual assets.",
    458: "FR20. The system shall provide an integrated operator interface for ingestion, analysis, decoder, providers, diagnostics, and visual assets.",
    462: "NFR1. The system shall complete narrative analysis and extraction within an acceptable time frame after story submission, with progress visibility for long-running jobs.",
    463: "NFR2. Decoder generation and regeneration processes shall provide results within reasonable response times based on story length and generation complexity.",
    464: "NFR3. Visual prompt generation and image rendering handoff shall be performed efficiently without causing unnecessary system delays.",
    465: "NFR4. Dashboard inspection and runtime status queries shall remain responsive during normal local operation.",
    467: "NFR5. The system architecture shall support increasing numbers of books, scenes, and long-running analysis requests within the local operational environment.",
    470: "NFR7. The operator interface shall be intuitive and easy to navigate for technical and non-technical reviewers.",
    474: "NFR10. The system shall maintain stable operation during extended analysis and generation sessions.",
    476: "NFR12. Uploaded sources, canonical records, generated stories, and visual outputs shall remain accessible throughout the active local workspace.",
    478: "NFR13. The system shall maintain consistency between persisted canonical analysis, decoder outputs, and visual prompt/render outputs.",
    479: "NFR14. Generated content and derived prompts shall preserve narrative continuity, character consistency, and story-world coherence across supported workflows.",
    481: "NFR15. User-uploaded content, canonical data, and generated outputs shall be protected against unauthorized access.",
    482: "NFR16. Access to uploaded books, generated stories, prompts, and visual assets shall be restricted to authorized local users or configured operators.",
    490: "Mistral and other open-weight model families remain valuable for local or semi-local deployment because they offer lower operational cost, self-hosting flexibility, and strong structured extraction performance. These models are especially useful for experimental narrative analysis, fallback generation paths, and cases where data locality matters. Their main limitations are lower peak reasoning quality compared with stronger hosted models and greater sensitivity to prompt and validation design.",
    492: "OpenAI-compatible hosted models provide strong reasoning, reliable schema-following behavior, and mature API ergonomics, which makes them well suited for planning-heavy tasks, constrained generation, and higher-trust validation loops. Their main limitations are higher cost, dependence on external APIs, and reduced control over runtime internals when compared with fully local deployments.",
    494: "Meta LLaMA and related open-weight families provide another strong self-hosted option with broad ecosystem support. They are suitable for experimentation, retrieval-assisted workflows, and selective prose generation, but they typically require more hardware and operational tuning than lighter open-weight alternatives.",
    496: "In the current system, no single model family is treated as the permanent architecture. Instead, the runtime abstracts provider choice through the reasoning runtime layer so that planning, prose generation, and analysis workloads can be assigned to different backends as reliability, cost, and quality needs evolve. This provider-agnostic design is more aligned with the current production path than the earlier prototype's fixed-model framing.",
    502: "SQLite is selected as the canonical operational database because it provides a simple, durable, and queryable local store that fits the current architecture of S.A.G.A. Unlike the earlier graph-first prototype, the production-oriented system persists books, chapters, scenes, entities, events, relationships, timelines, stable states, visual prompts, generated stories, and runtime jobs directly into a normalized SQLite schema. This design reduces synchronization overhead, simplifies deployment, improves resumability, and gives the dashboard and downstream services one authoritative source of truth. Optional graph-oriented services can still exist for selected retrieval experiments, but SQLite is the primary persistence layer of the current system.",
    504: "FastAPI Runtime",
    506: "Dashboard Pro (React)",
    508: "DatabaseAnalysisRunService",
    509: "The current orchestration stack is implemented through a layered local runtime rather than external workflow tools. FastAPI provides the HTTP runtime and job-control surface, Dashboard Pro provides the operator UI for uploads, runs, analysis, decoder, visuals, and diagnostics, and DatabaseAnalysisRunService coordinates validation, ingestion, identity preparation, stage execution, and progress tracking. Together, these components form the operational backbone of the current system and replace the earlier prototype's workflow-centric orchestration story.",
    511: "PyMuPDF",
    513: "EbookLib",
    515: "pypdf",
    517: "EPUB/PDF Processor Layer",
    518: "Among the evaluated source-processing approaches, the current system relies on a pragmatic file-type-specific ingestion layer rather than a vision-first OCR pipeline. EPUB sources are handled with EbookLib-based processing, PDF sources are handled through PyMuPDF and pypdf-backed extraction utilities, and both feed the same downstream chapter and scene preparation pipeline. This strategy better matches the current codebase, which prioritizes durable ingestion, provenance preservation, and narrative analysis over document-OCR experimentation.",
    552: "This figure illustrates the current S.A.G.A. system architecture as a database-native narrative intelligence pipeline. The analysis path begins with staged source ingestion, chapter extraction, and deterministic scene preparation, followed by BookNLP-clean identity construction and specialized database-native agents for events, entities, profiles, timelines, states, and visual artifacts. All extracted narrative data is written to a unified SQLite canonical store, which serves as the operational memory of the system. Downstream services then reuse this same persisted memory for dashboard review, decoder-driven story generation, retrieval, and visual prompt generation.",
    554: "Rather than separating analysis and generation through disconnected prototype artifacts, the current architecture centers the entire workflow on one canonical store and one local runtime. This allows S.A.G.A. to transform unstructured books into durable narrative memory and then reuse that memory for controlled extension, operator inspection, and visual continuity workflows.",
    564: "Figure 3.2 illustrates the current operator-oriented use case view of the S.A.G.A. platform. The diagram can be interpreted around three practical roles: the local operator who stages books and starts jobs, the analyst who reviews extracted canon and downstream outputs, and the administrator who manages provider/runtime health.",
    565: "The use case view further illustrates a staged internal workflow where story processing begins with import validation and database-native analysis. Uploaded books are decomposed into chapters and scenes, anchored by identity bundles, and then processed into events, entities, profiles, timelines, states, and visual prompts. These extracted elements serve as inputs to downstream workflows including decoder generation, visual rendering, and dashboard inspection. The system also supports local export options such as structured story text, EPUB, and generated image assets, enabling flexible analysis and output review.",
    566: "The S.A.G.A. system consists of three practical actor roles with different operational responsibilities, as shown in Table 3.1.",
    581: "The Level 0 Data Flow Diagram represents the current system as a single high-level narrative intelligence process and shows how it interacts with its main external role, the local operator.",
    582: "In this diagram, the operator provides source books and runtime configuration as input. These inputs represent one or more narrative works that will be ingested, segmented, analyzed, and persisted by the system.",
    583: "The main output of the system is structured canonical data stored in the SQLite canon store, together with generated stories, visual prompts, rendered assets, and dashboard-readable runtime state. The operator can later query or inspect this data to analyze narrative structures, relationships, state changes, and downstream outputs.",
    587: "Process: S.A.G.A. Narrative Intelligence System",
    588: "Data Flows:",
    1495: "The implementation supports decoder generation modes for pre-canon, mid-canon, post-canon, and alternate-universe runs, together with EPUB export of generated stories.",
    1552: "The Decoder is implemented as a Python backend service organized around the NarrativeGenerationService class and wrapped operationally by DatabaseDecoderService. This layer encapsulates the generation pre-step and staged generation flow, and it exposes entry points that load book context from the current SQLite-backed contract-like store rather than depending on the earlier prototype's graph-only path. The service remains effectively stateless between runs; generation state is maintained in runtime structures and persisted through generated artifacts and database records.",
    1553: "The Decoder depends on collaborating components provided by the broader S.A.G.A. system: an reasoning runtime that abstracts over multiple language model backends, retrieval and context-compilation services that assemble focused canon packets for each generation step, and a SQLite contract adapter that loads persisted story memory into a decoder-friendly form. This keeps generation grounded in the same canonical store used by the rest of the system.",
    1555: "The Decoder interfaces with language models through the reasoning runtime abstraction, which supports multiple backend modes. In the current implementation, provider choice is configurable and can vary between planning and prose generation. This allows the runtime to use stronger schema-following models for planning-heavy stages and different models for prose-heavy stages, while preserving a consistent service interface.",
    1556: "The service supports separate reasoning runtime instances for planning and prose generation, enabling independent configuration of model selection, temperature, and operational fallback behavior for each stage. If a preferred backend encounters rate limits or availability issues, the runtime can switch to a compatible alternative according to the configured provider logic.",
    1557: "4.2.3 Canonical Context and Retrieval Layer",
    1558: "The Decoder consumes narrative context from the persisted S.A.G.A. canonical store and from retrieval-oriented helper services that assemble focused context packets for the current generation step. This ensures that every generation step is grounded in the specific characters, relationships, events, and state information most relevant to the narrative moment being produced, rather than relying on a static undifferentiated memory dump.",
    1559: "4.2.3.1 SQLite-Backed Canon Store",
    1561: "The SQLite canon store serves as the primary persistent structured memory of the source book in the current system. It stores books, scenes, entities, events, relationships, timelines, stable states, prompts, generated stories, and job metadata in normalized tables. Decoder services load this persisted state through store and adapter layers, then convert it into a normalized retrieval context for planning and prose generation. Optional alternate retrieval backends may still exist, but the SQLite store is the authoritative production path.",
    1563: "The retrieval layer is responsible for assembling focused, per-step context from persisted canon artifacts. It selects the most relevant characters, relationships, events, unresolved threads, and memory documents for the current chapter or scene so that generation stays grounded in the narrative state most relevant to the requested output.",
    1588: "The constructor accepts optional reasoning runtime instances for planning and prose, an optional retriever, a target chapter count, and configurable operational parameters. If no reasoning runtime is provided, the service constructs a default backend configuration through the shared runtime abstractions. In the current architecture, decoder context is loaded through the database-backed adapter path and supporting retrieval services rather than a hardwired graph-only dependency.",
    1609: "The Decoder saves generated artifacts to a configurable output directory and also stores generated-story records and verification metadata back into SQLite. Table 4.1 illustrates the primary files produced by a generation run.",
    1612: "The Decoder records retrieval debug snapshots after each chapter and scene for inspection and evaluation. These snapshots summarize the query context, surfaced memories, and included character packets, enabling post-hoc analysis of which canonical memories were used at each generation step and how retrieval quality evolved across the run.",
    1614: "The Decoder's runtime defaults and provider behavior are defined through service-level configuration and shared provider abstractions, enabling straightforward substitution of alternative models without rewriting generation logic. Pause durations, chapter targets, and generation controls remain configurable so that long-running story generation can be tuned to the local runtime environment.",
    1615: "The decoder entry points support reuse of previously exported contexts and generated planning artifacts when they remain compatible with the current generation request. This enables iterative runs that avoid repeating unnecessary planning work while staying aligned with the persisted canonical store.",
    1623: "4.3 Dashboard Runtime and Review Surface",
    1624: "4.3.1 Runtime Entry Surface",
    1625: "The dashboard runtime receives upload, analysis, decoder, and visual-workflow requests from the local operator surface.",
    1626: "Requests are validated by the FastAPI layer, translated into structured service calls, and persisted as database-backed jobs, uploads, or output records that can be inspected later through the dashboard.",
    1627: "Example:",
    1628: "Upload book -> Validate import plan -> Run DB-native analysis -> Inspect outputs",
    1629: "Each action is therefore traceable through a persisted runtime state rather than a transient one-shot script call.",
    1630: "4.3.2 API and Job Construction",
    1631: "The runtime communicates with analysis, decoder, and visual services through Python service classes rather than embedding business logic inside the frontend. Each request carries structured payloads describing series metadata, selected books, generation controls, provider preferences, or rendering parameters.",
    1632: "The backend validates these payloads, writes job progress and logs to SQLite, and exposes the resulting state through dashboard endpoints. This design makes long-running operations observable and reduces ambiguity about what the system is doing at any moment.",
    1633: "4.3.3 Review Workflow",
    1634: "The review workflow consists of several sequential stages. First, the operator stages one or more books and validates an import plan. The runtime then performs ingestion, identity preparation, and optional DB-agent execution. After persistence is complete, the dashboard can inspect scenes, entities, events, profiles, timelines, stable states, prompts, and generated stories.",
    1635: "Because these artifacts remain in SQLite, the user can move between analysis, decoder, and visual pages without losing the canonical context established earlier in the run.",
    1636: "4.3.4 Challenges and Observations",
    1637: "Several challenges were encountered during development:",
    1639: "Long-Running Job Coordination",
    1640: "Analysis runs may span large books and multiple agent stages, so the runtime must persist progress carefully and expose safe cancellation or retry boundaries without pretending that unsupported pause or resume behavior exists.",
    1641: "Operational Transparency",
    1642: "Earlier prototype-style workflows made it difficult to see where failures occurred. The current dashboard resolves this by surfacing provider health, job logs, progress payloads, and persisted outputs directly to the operator.",
    1643: "Safe Control Boundaries",
    1644: "Some lifecycle controls are intentionally conservative because misleading controls are worse than missing controls. The system therefore favors explicit retry and cancel paths over fake resumability claims.",
    1646: "4.4 Visual Prompting and Rendering Integration",
    1647: "4.4.1 Structured Prompt Generation",
    1648: "The current visual pipeline is centered on structured prompt generation rather than standalone image synthesis prompts. EntityVisualPromptService compiles canonical prompt payloads from SQLite-backed entities, visual baselines, world state, and scene-aware information.",
    1649: "ComfyUICharacterSheetService and related render utilities then convert these prompt payloads into render-ready workflows for character sheets and other grounded visual assets.",
    1650: "This design keeps visual generation tied to the same canonical memory used elsewhere in the system, improving continuity between analysis and rendering.",
    1651: "4.4.2 Visual Workflow",
    1652: "The visual workflow consists of the following stages:",
    1653: "Load the canonical entity or scene context from the SQLite store.",
    1654: "Resolve baseline traits together with current scene-level state.",
    1655: "Build a versioned visual prompt payload.",
    1656: "Dispatch a render workflow or save the prompt for later rendering.",
    1657: "Persist generated assets, manifests, and supporting metadata.",
    1658: "Expose the results through dashboard visual-asset views.",
    1659: "The resulting outputs remain traceable to the source book, entity, and prompt version used to produce them.",
    1660: "4.4.3 Output Management",
    1661: "To support grounded visual generation, each rendered image is linked back to its corresponding prompt and canonical entity metadata whenever possible. This keeps prompt lineage explicit and makes later review, regeneration, or comparison easier.",
    1662: "Generated images and supporting exports remain compatible with the local analysis_outputs workspace and the dashboard's visual browsing surfaces.",
    1663: "4.4.4 Challenges and Observations",
    1664: "Several challenges were encountered during development:",
    1665: "Visual Consistency",
    1666: "Maintaining continuity across multiple renders requires more than repeating a character name. The system therefore persists baseline traits and later scene-specific changes so prompts can be rebuilt from canonical memory rather than from isolated scene summaries.",
    1667: "Prompt Provenance",
    1668: "Prompt quality is easier to improve when the exact prompt record, source entity, and render metadata are preserved. This motivated storing prompts and outputs as first-class persisted artifacts instead of throwaway text blobs.",
    1669: "Provider and Workflow Variability",
    1670: "Rendering workflows may evolve faster than the core analysis schema. The integration layer therefore isolates renderer-specific details while preserving a stable canonical prompt contract.",
    1671: "Storage and Review",
    1672: "Visual assets must remain easy to inspect after generation, so thumbnails, manifests, and persistent references are treated as part of the workflow rather than post-processing afterthoughts.",
    1680: "4.5 Deployment and Local Operation",
    1681: "4.5.1 Dashboard Structure and User Interface",
    1682: "The current S.A.G.A. interface is a local dashboard surface composed of a React frontend and a FastAPI runtime. The frontend is Dashboard Pro. Main pages include Overview, Import, Runs, Library, Analysis, Decoder, Visual Assets, Providers, and Diagnostics.",
    1683: "This interface is designed for operator review and workflow control rather than for a public consumer-facing website. Navigation focuses on ingesting books, inspecting canonical memory, launching downstream workflows, and monitoring runtime health.",
    1684: "4.5.2 Runtime and Service Management",
    1685: "Local execution is provided through Windows launcher scripts and an optional background service configuration. The runtime can be started directly for development use or registered as a local service for persistent operation.",
    1686: "1) Local Launch",
    1687: "A standard launch path builds the frontend if needed, starts the FastAPI runtime, and exposes the dashboard at the default local address 127.0.0.1:8675.",
    1689: "2) Background Service",
    1690: "Service installation scripts can register the dashboard runtime as a persistent Windows service so the interface remains available without manually starting the stack each time.",
    1693: "3) Provider Configuration",
    1694: "Provider accounts and backend configuration are managed locally through deployment files and surfaced through dashboard health views. This allows operators to inspect whether the configured backends are ready before starting long-running jobs.",
    1695: "4) Session and Job Management",
    1696: "Jobs are persisted in SQLite with logs, progress, and artifacts. The system supports safe cancellation and retry paths where implemented, and it avoids exposing unsupported control semantics as if they already existed.",
    1697: "5) Upload and Output Management",
    1698: "Uploaded sources, story exports, rendered assets, and other generated artifacts are stored in local workspace directories and referenced from the canonical store so they remain discoverable through the dashboard.",
    1699: "This local-first deployment model keeps the current system practical for research, experimentation, and operator-driven review without requiring a hosted multi-user platform.",
    1701: "4.5.3 Core Workflow Modules",
    1702: "1) Analysis Pipeline Module",
    1703: "The analysis path serves as the foundation of S.A.G.A. It stages books, validates import plans, builds identity bundles, ingests chapters and scenes, and runs the DB-native agent stages that populate the canonical store with events, entities, profiles, timelines, states, and prompt-ready visual data.",
    1704: "These persisted outputs then become the basis for dashboard inspection, decoder workflows, and visual rendering support.",
    1705: "2) Visual Assets Module",
    1706: "The Visual Assets workflow enables users to inspect prompt records, start character-sheet or scene render jobs, and review generated images together with their canonical provenance.",
    1707: "This module connects the narrative-analysis layer to concrete image-generation workflows without severing the link back to stored canon data.",
    1709: "3) Decoder Module",
    1710: "The Decoder workflow creates canon-aware narrative outputs from persisted story memory. Users can select generation modes such as pre-canon, mid-canon, post-canon, or alternate-universe runs, then review the generated stories through the same runtime surface.",
    1711: "Generated stories remain attached to the source book, controls, provider metadata, and verification results, which makes later review and iteration significantly easier.",
    1712: "4.5.4 Service Integration Workflow",
    1713: "The current runtime integrates ingestion, analysis, dashboard review, decoder generation, and visual rendering through one local canonical store. This shared-storage model is what allows S.A.G.A. to behave as one coherent narrative intelligence system instead of a collection of disconnected scripts.",
    1736: "The S.A.G.A. project represents a substantial shift from prototype storytelling experimentation toward a production-oriented narrative intelligence workflow. By moving from artifact-fragmented processing to database-native canonical memory, the system addresses key limitations of earlier AI storytelling systems and of the team's own legacy prototype, especially around consistency, resumability, identity stability, and operational review.",
    1737: "S.A.G.A. presents an integrated AI-driven platform that combines narrative understanding, canonical persistence, dashboard inspection, controlled story generation, and visual prompting within a unified local framework. By analyzing existing stories and extracting structured narrative knowledge into SQLite, the system is able to support coherent downstream generation and visual continuity while preserving character consistency, event logic, and overall story coherence.",
    1738: "The development of S.A.G.A. demonstrates the value of combining natural language processing, structured persistence, staged agent design, retrieval-aware generation, and image-generation support around one shared canonical memory. The project shows that reusable story intelligence is more powerful than one-shot prompting alone and provides a strong foundation for future work in canon-aware querying, rewrite planning, and richer narrative tooling.",
    1740: "Future versions of S.A.G.A. may incorporate richer character memory, deeper relationship and world-state synthesis, and stronger point-in-time query services that can answer canon questions at specific events or scenes. Additional narrative analysis techniques could also be integrated to capture deeper thematic, emotional, and symbolic relationships within stories.",
    1741: "5.2.1 Point-in-Time Querying and Rewrite Planning",
    1742: "A major next step is the expansion of event-anchored query APIs and divergence planning workflows. Future versions may support functions such as snapshot_before(event_id), snapshot_after(event_id), richer dependency tracing, stable-versus-unstable downstream fact classification, and grounded rewrite-outline generation for controlled mid-canon divergence.",
    1743: "These capabilities would extend S.A.G.A. from a canon-aware generation system into a stronger rewrite-planning environment capable of supporting alternate timelines and continuity-safe authoring with much finer control.",
    1744: "5.2.2 Interactive Review and Multilingual Extensions",
    1745: "Future versions of S.A.G.A. may introduce richer interactive review tools that allow users to compare runs, inspect ambiguity more explicitly, and collaborate more effectively around canonical evidence and generated outputs.",
    1746: "Expanding support for multiple languages, larger story repositories, and broader source collections would improve accessibility and broaden the applicability of S.A.G.A. to diverse audiences, cultures, and literary domains.",
    1747: "Further enhancements may include richer dashboard controls for scenario comparison, more configurable decoder constraints, and stronger retrieval analytics that explain why specific memories were surfaced during generation.",
    1748: "5.2.3 Reliability and Ethical Considerations",
    1749: "Future work may focus on improving robustness and efficiency through stronger consistency-checking mechanisms, better provider orchestration, deeper validation frameworks, and more automated detection of narrative contradictions across persisted canon, generated stories, and visual prompts.",
    1750: "S.A.G.A. must also address important ethical considerations. Because the system analyzes existing stories to extract narrative structure and storytelling patterns, adherence to intellectual property and copyright regulations remains essential. The platform is intended for use with public-domain works, properly licensed content, or user-owned materials. In addition, content safety remains a critical concern due to the generative nature of downstream workflows. Validation, moderation, and operator review should therefore remain integral parts of the pipeline to support responsible and secure use of artificial intelligence in creative storytelling applications.",
    275: "6) Lack of Integrated Operational Review",
    276: "Most storytelling systems focus primarily on text generation and offer limited support for inspecting canonical memory, runtime health, and the grounded evidence behind their outputs.",
    308: "Understanding how stories are structured and written by humans is essential for building a system capable of modifying, extending, or regenerating narratives. This chapter presents the process of investigating, prompting, and analyzing the system requirements for S.A.G.A. The requirements were extracted using structured domain research focused on story structure, narrative theories, and the human writing workflow, which was treated as the main requirements gathering instrument.",
    321: "These stages form the functional foundation that S.A.G.A. supports through AI-based analysis, persistence, and controlled generation.",
    343: "To collect user requirements for the proposed S.A.G.A. system, an online questionnaire was designed and distributed using Google Forms. The questionnaire targeted individuals interested in storytelling and creative media, including readers, writers, designers, and content creators. The purpose of the survey was to understand users' storytelling habits, experience with AI tools, and expectations from an intelligent storytelling system. We gathered a total of 130 responses.",
    596: "The Level 1 Data Flow Diagram expands the system into its main internal processes and shows how data flows between them. This diagram provides a detailed view of how source books are transformed into persistent canonical data and downstream workflow artifacts.",
    597: "The process begins when the operator provides one or more source books. These files are first passed to the ingestion and preprocessing layer, where file parsing, chapter extraction, and source normalization are performed before deeper analysis begins.",
    598: "In the next phase, the normalized content is divided into chapters and scenes and is assigned provenance metadata such as book order, chapter index, and scene index. These persisted units are then passed to the identity and narrative analysis stages.",
    599: "During narrative extraction, key entities such as characters, scenes, and events are identified. Relationships, timelines, state changes, and visual descriptors are then derived and normalized into canonical records that can support later dashboard, decoder, and visual workflows.",
    600: "Finally, the processed data is sent to the canonical persistence layer, where books, scenes, identities, entities, events, relationships, prompts, and job state are stored in SQLite. The stored data can later be accessed for querying, visualization, generation, or further analysis.",
    602: "Ingestion and Preprocessing",
    603: "Chapter and Scene Persistence",
    604: "Identity and Narrative Analysis",
    605: "Canonical Data Normalization",
    606: "Storage in SQLite Canon Store",
    608: "SQLite Canon Store",
    613: "Canonical Data -> SQLite",
    639: "To achieve the primary objectives of the current system, we adopted a hybrid narrative-analysis methodology that combines deterministic preprocessing, identity-first normalization, staged agent analysis, and persistent canonical storage. This methodology addresses the limitations of pure Large Language Model (LLM) generation by grounding downstream workflows in structured extracted data rather than in transient prompts alone.",
    1064: "These improvements transform the encoder from a proof-of-concept narrative analysis pipeline into a production-oriented narrative intelligence framework capable of supporting the broader objectives of the current S.A.G.A. system.",
    1078: "The Decoder constitutes the controlled narrative generation stage within the S.A.G.A. system. The full system comprises several interconnected stages including story ingestion, canonical persistence, context retrieval, dashboard review, and narrative generation. The Decoder is responsible for producing canon-aware narrative content grounded in a source book's established world, characters, events, and relationships.",
    1079: "The Decoder receives its inputs from the encoder and from retrieval context assembled from the persisted canonical store together with retrieval helpers that surface the most relevant memories for the requested generation step. It then applies a staged generation architecture to produce narrative content that faithfully extends or reimagines the source material according to the user's creative direction.",
    1108: "Before any generation begins, the Decoder performs a context compilation step using structured data produced by the earlier stages of the encoder. This pre-step is not itself a generation stage; instead, it transforms the raw retrieval context containing character states, relationship summaries, unresolved threads, causal signals, flexible events, trajectories, and recent ending state from the persisted canonical store into a curated compiled context ready for generation.",
    1230: "3.5 Runtime, Provider, and Review Infrastructure",
    1231: "3.5.1 Operational Runtime Methodology",
    1232: "3.5.1.1 Objective",
    1233: "The objective of the runtime layer is to coordinate long-running analysis, decoder, and visual workflows while keeping progress observable and recoverable. Rather than treating each workflow as an isolated script, the system records jobs, outputs, and supporting metadata in a persistent operational store.",
    1234: "This runtime layer therefore acts as the bridge between canonical analysis, downstream generation, and the operator-facing dashboard.",
    1235: "3.5.1.2 Service-Oriented Coordination Approach",
    1236: "A service-oriented orchestration approach was adopted for the current system. The FastAPI runtime receives structured requests, validates them, and delegates execution to dedicated service classes such as DatabaseAnalysisRunService and DatabaseDecoderService. This approach keeps business logic in reusable backend components while allowing the dashboard to remain a thin operator surface.",
    1237: "3.5.1.3 Provider Configuration and Runtime Strategy",
    1238: "During development, multiple provider configurations were evaluated to determine how best to balance cost, reliability, and output quality across analysis and generation workloads. The current system supports local and hosted backends through the reasoning runtime abstraction rather than hardwiring the architecture to a single model family.",
    1239: "Local or semi-local backends are useful for lower-cost experimentation and continuous testing, while stronger hosted models are useful for planning-heavy or validation-heavy steps that benefit from better reasoning quality.",
    1240: "Because different runtime stages place different demands on the model, the system allows planning and prose generation to use distinct provider configurations when needed.",
    1241: "Provider status is surfaced through dashboard diagnostics so operators can make informed choices before starting long-running jobs.",
    1242: "This provider abstraction preserves operational flexibility while keeping the overall pipeline consistent from the perspective of the rest of the system.",
    1243: "Structured validation, explicit progress tracking, and provider-aware retry logic are treated as runtime responsibilities rather than as ad hoc scripting details.",
    1244: "3.5.1.4 Job Control and Persistence",
    1245: "The analysis runtime validates import plans, builds identity bundles, ingests books, and executes DB-native stages while writing progress updates and artifacts to SQLite. The decoder runtime similarly loads canonical context, executes generation, verifies outputs, and stores the resulting story records together with metadata.",
    1246: "This separation allows each long-running workflow to evolve independently while still relying on the same canonical storage and shared runtime conventions.",
    1247: "3.5.1.5 Runtime Outputs",
    1248: "The output of the runtime stage is not only the final generated artifact, but also the surrounding operational state: jobs, logs, progress payloads, persisted outputs, provider metadata, and verification records.",
    1249: "This design creates a modular system where analysis, generation, and review can operate as distinct services without losing continuity between stages.",
    1250: "3.5.2 Dashboard Review Methodology",
    1251: "3.5.2.1 Dashboard Objective",
    1252: "The objective of the dashboard layer is to expose canonical memory and workflow state through a practical local interface suitable for inspection, control, and troubleshooting. Instead of forcing the operator to inspect raw files or logs directly, the dashboard presents structured views over the persisted data.",
    1253: "By reading directly from the same canonical and runtime stores used by the backend services, the dashboard becomes a review surface rather than a disconnected visualization layer.",
    1254: "3.5.2.2 Review Approach",
    1255: "A modular review approach was adopted for the dashboard. Individual pages query backend endpoints for library data, analysis sections, provider health, visual assets, generated stories, and diagnostic information, allowing each view to focus on one operational concern without losing access to the shared underlying context.",
    1256: "This approach improves inspectability of long-running jobs, makes failures easier to localize, and supports targeted iteration on specific parts of the system.",
    1257: "3.5.2.3 Surface Composition",
    1258: "The current dashboard surface includes pages such as Overview, Import, Runs, Library, Analysis, Decoder, Visual Assets, Providers, and Diagnostics. Together, these views expose the production path of the system more clearly than the earlier prototype's file-heavy workflow.",
    1259: "The interface emphasizes canonical browsing, job progress visibility, provider readiness, and provenance-aware access to generated outputs.",
    1260: "Visual assets and generated stories are presented alongside the metadata needed to understand how they were produced and how they relate back to the analyzed source material.",
    1261: "Several factors influenced the final dashboard design:",
    1262: "Inspectability of long-running jobs.",
    1263: "Clear separation between analysis, generation, and rendering actions.",
    1264: "Support for persisted provenance and reproducibility.",
    1265: "Responsive local navigation over SQLite-backed records.",
    1266: "Ease of integration with provider diagnostics and generated outputs.",
    1267: "Based on implementation experience, the dashboard was selected as the primary operational surface because it exposes the database-native system more transparently and safely than script-only workflows.",
    1268: "3.5.2.4 Dashboard Outputs",
    1269: "The dashboard presents persisted records, generated stories, prompt artifacts, rendered assets, provider status, and runtime progress in one operator-facing environment.",
    1270: "Each workflow output remains linked to canonical source data and job history, enabling later review, troubleshooting, and controlled iteration.",
    1306: "This chapter presents the implementation of the S.A.G.A. Encoder, which transforms raw literary works into structured narrative knowledge that can be used for retrieval, canon-aware generation, event divergence, and visual downstream workflows.",
}


TABLE_UPDATES: dict[tuple[int, int, int], str] = {
    (1, 0, 6): "S.A.G.A.",
    (1, 9, 0): "Canon-aware generation grounded in extracted memory",
    (1, 9, 1): "No",
    (1, 9, 2): "No",
    (1, 9, 3): "No",
    (1, 9, 4): "No",
    (1, 9, 5): "No",
    (1, 9, 6): "Yes",
    (1, 10, 0): "Primary outputs",
    (1, 10, 1): "Text",
    (1, 10, 2): "Text + Image",
    (1, 10, 3): "Text + Image",
    (1, 10, 4): "Image + Video",
    (1, 10, 5): "Text",
    (1, 10, 6): "Structured Memory + Text + Image",
    (3, 9, 0): "Grounded visual prompt generation",
    (3, 9, 1): "Visual Prompt Service & Rendering Integration",
    (3, 10, 0): "Reviewing generated stories and canonical outputs",
    (3, 10, 1): "Dashboard Review, Library, and Output Inspection Modules",
    (5, 1, 0): "Local Operator",
    (5, 1, 1): "Primary user running the local dashboard and workflows.",
    (5, 1, 2): "Stage uploads, validate import plans, start jobs, inspect analyses, launch decoder and visual workflows",
    (5, 2, 0): "Project Analyst",
    (5, 2, 1): "Researcher or reviewer focused on extracted canon quality and downstream outputs.",
    (5, 2, 2): "Inspect scenes, entities, events, states, prompts, generated stories, and diagnostics",
    (5, 3, 0): "System Administrator",
    (5, 3, 1): "Maintainer responsible for runtime stability and provider configuration.",
    (5, 3, 2): "Manage providers, monitor service health, maintain local deployment, and review failures",
    (6, 1, 0): "Stage Uploads",
    (6, 1, 1): "Allows the operator to stage source books and supporting files for processing.",
    (6, 2, 0): "Validate Import Plan",
    (6, 2, 1): "Checks selected books, ordering, and runtime configuration before a long-running job begins.",
    (6, 3, 0): "Run DB-Native Analysis",
    (6, 3, 1): "Extracts chapters, scenes, identities, entities, events, timelines, states, and visual data into SQLite.",
    (6, 4, 0): "Inspect Canonical Memory",
    (6, 4, 1): "Lets the user review scenes, entities, events, relationships, profiles, prompts, and runtime results.",
    (6, 5, 0): "Generate Decoder Story",
    (6, 5, 1): "Creates a canon-aware narrative output grounded in the persisted source-book memory.",
    (6, 6, 0): "Render Visual Assets",
    (6, 6, 1): "Converts structured visual prompts into character-sheet or scene-based rendered outputs.",
    (6, 7, 0): "Review Generated Stories",
    (6, 7, 1): "Allows the operator to inspect generated stories, metadata, and verification details.",
    (6, 8, 0): "Launch Divergence Scenario",
    (6, 8, 1): "Starts an alternate-universe or continuity-controlled generation run from persisted canon.",
    (6, 9, 0): "Inspect Visual Results",
    (6, 9, 1): "Displays generated visual assets together with prompt and entity provenance.",
    (6, 10, 0): "Export Results",
    (6, 10, 1): "Allows users to export generated story text, EPUB outputs, and rendered visual assets.",
}


def update_paragraph(paragraph, new_text: str) -> bool:
    if paragraph.text == new_text:
        return False
    paragraph.text = new_text
    return True


def main() -> None:
    if not DOC_PATH.exists():
        raise FileNotFoundError(DOC_PATH)

    if not BACKUP_PATH.exists():
        shutil.copy2(DOC_PATH, BACKUP_PATH)

    doc = Document(str(DOC_PATH))

    changed_paragraphs = 0
    for index, new_text in PARAGRAPH_UPDATES.items():
        if index >= len(doc.paragraphs):
            raise IndexError(f"Paragraph index {index} out of range")
        if update_paragraph(doc.paragraphs[index], new_text):
            changed_paragraphs += 1

    changed_cells = 0
    for (table_idx, row_idx, col_idx), new_text in TABLE_UPDATES.items():
        table = doc.tables[table_idx]
        cell = table.rows[row_idx].cells[col_idx]
        if cell.text != new_text:
            cell.text = new_text
            changed_cells += 1

    doc.save(str(DOC_PATH))
    print(f"Updated {changed_paragraphs} paragraphs and {changed_cells} table cells in {DOC_PATH}")
    print(f"Backup: {BACKUP_PATH}")


if __name__ == "__main__":
    main()

