import { request, toQuery } from "./client";

export const runtimeApi = {
  state: () => request("/runtime/state"),
  jobs: () => request("/runtime/jobs"),
  job: (jobId) => request(`/runtime/jobs/${encodeURIComponent(jobId)}`),
  jobLogs: (jobId, params) => request(`/runtime/jobs/${encodeURIComponent(jobId)}/logs${toQuery(params)}`),
  jobControl: (jobId, action) => request(`/runtime/jobs/${encodeURIComponent(jobId)}/${action}`, { method: "POST" }),
  series: () => request("/runtime/series"),
  seriesBooks: (seriesId) => request(`/runtime/series/${encodeURIComponent(seriesId)}/books`),
  bookAnalysis: (bookRef, params = {}) => request(`/runtime/books/${encodeURIComponent(bookRef)}/analysis${toQuery(params)}`),
  uploads: () => request("/runtime/uploads"),
  uploadBatch: (formData) => request("/runtime/uploads/batch", { method: "POST", body: formData }),
  removeUpload: (sourceId) => request(`/runtime/uploads/${encodeURIComponent(sourceId)}`, { method: "DELETE" }),
  createImportPlan: (payload) => request("/runtime/import-plans", { method: "POST", body: JSON.stringify(payload) }),
  importPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}`),
  validateImportPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}/validate`, { method: "POST" }),
  startImportPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}/start`, { method: "POST" }),
  decoderOptions: () => request("/runtime/decoder/options"),
  validateDecoderPlan: (payload) => request("/runtime/decoder/plans/validate", { method: "POST", body: JSON.stringify(payload) }),
  startDecoder: (payload) => request("/runtime/decoder/jobs", { method: "POST", body: JSON.stringify(payload) }),
  stories: () => request("/runtime/stories"),
  story: (storyId) => request(`/runtime/stories/${encodeURIComponent(storyId)}`),
  assets: (params = {}) => request(`/runtime/assets/entities${toQuery(params)}`),
  asset: (entityId) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}`),
  savePromptVersion: (entityId, payload) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/prompt-versions`, { method: "POST", body: JSON.stringify(payload) }),
  renderEntity: (entityId, payload = {}) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/render`, { method: "POST", body: JSON.stringify(payload) }),
  renderBatch: (payload) => request("/runtime/assets/render-batch", { method: "POST", body: JSON.stringify(payload) }),
  providerStatuses: (refresh = false) => request(`/runtime/providers/status${refresh ? "?refresh=1" : ""}`),
};
