import { request, toQuery } from "./client";
import { audiobookRunBundleUrl as resolveAudiobookRunBundleUrl } from "./artifactUrls";

export const runtimeApi = {
  state: () => request("/runtime/state"),
  jobs: () => request("/runtime/jobs"),
  job: (jobId) => request(`/runtime/jobs/${encodeURIComponent(jobId)}`),
  jobLogs: (jobId, params) => request(`/runtime/jobs/${encodeURIComponent(jobId)}/logs${toQuery(params)}`),
  jobControl: (jobId, action) => request(`/runtime/jobs/${encodeURIComponent(jobId)}/${action}`, { method: "POST" }),
  series: () => request("/runtime/series"),
  seriesBooks: (seriesId) => request(`/runtime/series/${encodeURIComponent(seriesId)}/books`),
  audiobookRuns: (params = {}) => request(`/runtime/audiobook/runs${toQuery(params)}`),
  audiobookRun: (runId) => request(`/runtime/audiobook/runs/${encodeURIComponent(runId)}`),
  stageAudiobookRun: (payload) => request("/runtime/audiobook/runs/stage", { method: "POST", body: JSON.stringify(payload) }),
  startAudiobookJob: (payload) => request("/runtime/audiobook/jobs", { method: "POST", body: JSON.stringify(payload) }),
  startAudiobookRun: (runId) => request(`/runtime/audiobook/runs/${encodeURIComponent(runId)}/start`, { method: "POST" }),
  audiobookChapterAudioUrl: (runId, chapterId) => `/runtime/audiobook/runs/${encodeURIComponent(runId)}/chapters/${encodeURIComponent(chapterId)}/audio`,
  audiobookRunAudioUrl: (runId) => `/runtime/audiobook/runs/${encodeURIComponent(runId)}/audio`,
  audiobookRunBundleUrl: (runOrId) => resolveAudiobookRunBundleUrl(runOrId),
  bookAnalysis: (bookRef, params = {}) => request(`/runtime/books/${encodeURIComponent(bookRef)}/analysis${toQuery(params)}`),
  uploads: () => request("/runtime/uploads"),
  uploadBatch: (formData) => request("/runtime/uploads/batch", { method: "POST", body: formData }),
  removeUpload: (sourceId) => request(`/runtime/uploads/${encodeURIComponent(sourceId)}`, { method: "DELETE" }),
  createImportPlan: (payload) => request("/runtime/import-plans", { method: "POST", body: JSON.stringify(payload) }),
  importPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}`),
  validateImportPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}/validate`, { method: "POST" }),
  startImportPlan: (planId) => request(`/runtime/import-plans/${encodeURIComponent(planId)}/start`, { method: "POST" }),
  decoderOptions: () => request("/runtime/decoder/options"),
  validateDecoderPlan: (payload) => request("/runtime/decoder/plans/validate", { method: "POST", body: JSON.stringify(payload) }),
  startDecoder: (payload) => request("/runtime/decoder/jobs", { method: "POST", body: JSON.stringify(payload) }),
  stories: () => request("/runtime/stories"),
  story: (storyId) => request(`/runtime/stories/${encodeURIComponent(storyId)}`),
  assetSeriesSummary: () => request("/runtime/assets/series-summary"),
  assets: (params = {}) => request(`/runtime/assets/entities${toQuery(params)}`),
  asset: (entityId) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}`),
  renameAssetEntity: (entityId, payload) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}`, { method: "PATCH", body: JSON.stringify(payload) }),
  savePromptVersion: (entityId, payload) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/prompt-versions`, { method: "POST", body: JSON.stringify(payload) }),
  renderEntity: (entityId, payload = {}) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/render`, { method: "POST", body: JSON.stringify(payload) }),
  previewRenderEntity: (entityId, payload) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/preview-render`, { method: "POST", body: JSON.stringify(payload) }),
  saveRenderedEntity: (entityId, payload) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}/save-render`, { method: "POST", body: JSON.stringify(payload) }),
  deleteAssetEntity: (entityId) => request(`/runtime/assets/entities/${encodeURIComponent(entityId)}`, { method: "DELETE" }),
  renderBatch: (payload) => request("/runtime/assets/render-batch", { method: "POST", body: JSON.stringify(payload) }),
  providerStatuses: (refresh = false) => request(`/runtime/providers/status${refresh ? "?refresh=1" : ""}`),
  inferenceProvider: (providerName) => request(`/runtime/inference/providers/${encodeURIComponent(providerName)}`),
  saveInferenceProvider: (providerName, payload) =>
    request(`/runtime/inference/providers/${encodeURIComponent(providerName)}`, { method: "POST", body: JSON.stringify(payload) }),
};
