from pathlib import Path
p = Path(__file__).resolve().parents[1] / 'docs/studio-ui-polish-checklist.md'
text = p.read_text()
text = text.replace("## Current iteration\n\n**Platform blocker — Modal ecosystem worker fleet**\n\n- Status: `[~]` in progress\n- Completed checklist items remain **01–11**.\n- Blocker: replace the single-account Modal runtime assumption with ecosystem-affine workers, scale-to-zero compute, persistent model caches, credit/unavailable failover, clean worker provisioning, and production worker-state feedback.\n- Item **12 — improve generation lifecycle feedback** remains pending and must not start until this blocker is implemented and end-to-end generation is validated.", "## Current iteration\n\n**P1 core UX and architecture — complete**\n\n- Status: `[x]` Items **01–20** complete.\n- Modal ecosystem worker-fleet migration and real worker-state feedback are implemented and validated.\n- Next planned polish scope begins at **Item 21** in P2.")
old = "- [~] **20. Split App.jsx responsibilities.** Implementation in validation: generation lifecycle moved to `useGenerationController`, Gallery/Favorites/Collections state/loading moved to `useLibraryController`, Gallery selection moved to `useGallerySelection`, item/bulk/collection mutations moved to `useMediaActions`, and browser API calls are consolidated in `api/studioApi.js`."
new = "- [x] **20. Split App.jsx responsibilities.** Generation lifecycle now lives in `useGenerationController`; Gallery/Favorites/Collections state/loading in `useLibraryController`; Gallery selection in `useGallerySelection`; item, bulk, and collection mutations in `useMediaActions`; browser API operations are consolidated in `api/studioApi.js`. Worker/lifecycle contract tests were updated to follow the new ownership rather than requiring implementation inside `App.jsx`. Final artifact `9530241337` from Studio Visual Preview `32754253022` was manually inspected across desktop Gallery, 390px mobile Manage, and active generation-progress states with no visual regression. Validated by Studio CI `32754253028`, Studio Visual Preview `32754253022`, Backend Architecture CI `32754253027`, Modal Worker Inventory `32754253032`, Worker Fleet Live Smoke `32754253050`, and Required Check Compatibility `32754253049`. **Iteration 20 complete; P1 complete.**"
if old not in text:
    raise SystemExit('Item 20 in-progress line not found')
p.write_text(text.replace(old, new))
print('Iteration 20 completion recorded.')
