from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def replace_once(path: str, old: str, new: str) -> None:
    content = read(path)
    if old not in content:
        raise SystemExit(f"Expected patch anchor not found in {path}: {old[:120]!r}")
    write(path, content.replace(old, new, 1))


def append_once(path: str, marker: str, addition: str) -> None:
    content = read(path)
    if marker in content:
        return
    write(path, content.rstrip() + "\n\n" + addition.strip() + "\n")


# Record the platform blocker before product implementation, without starting Item 12.
replace_once(
    "docs/studio-ui-polish-checklist.md",
    """## Current iteration\n\n**Iteration 11 — explicit Audio state**\n\n- Status: `[x]` complete\n- Completed item: **11**\n- Next item: **12 — improve generation lifecycle feedback**\n- Rule: do not start Item 12 until the user explicitly says continue. Each future iteration must follow implement → deterministic test → GitHub CI/visual preview → inspect screenshots → professional critique → record improvements → update this file → stop for user approval.\n""",
    """## Current iteration\n\n**Platform blocker — Modal ecosystem worker fleet**\n\n- Status: `[~]` in progress\n- Completed checklist items remain **01–11**.\n- Blocker: replace the single-account Modal runtime assumption with ecosystem-affine workers, scale-to-zero compute, persistent model caches, credit/unavailable failover, clean worker provisioning, and production worker-state feedback.\n- Item **12 — improve generation lifecycle feedback** remains pending and must not start until this blocker is implemented and end-to-end generation is validated.\n""",
)

ECOSYSTEMS = {
    "version": 1,
    "ecosystems": [
        {
            "id": "flux2-klein-9b",
            "displayName": "FLUX.2 Klein 9B",
            "workflowIds": ["flux2-klein-image-edit"],
            "runtimeEntrypoint": "integrations/comfyui/flux2_klein_app.py",
            "runtimeApp": "saga-flux2-klein-9b",
            "runtimeClass": "Flux2KleinWorker",
            "gatewayEntrypoint": "integrations/comfyui/flux2_klein_gateway.py",
            "gatewayApp": "saga-flux2-klein-gateway",
            "gatewayFunction": "web",
            "volume": "saga-flux2-klein-9b-cache",
            "stateDict": "saga-flux2-klein-9b-worker-state",
            "idleSeconds": 180,
            "maxConcurrency": 1,
        },
        {
            "id": "ltx25-redgraft",
            "displayName": "REDGraft LTX 2.5",
            "workflowIds": ["ltx25-redgraft-video"],
            "runtimeEntrypoint": "integrations/comfyui/ltx23_app.py",
            "runtimeApp": "saga-ltx25-video",
            "runtimeClass": "LTX25Worker",
            "gatewayEntrypoint": "integrations/comfyui/ltx23_gateway.py",
            "gatewayApp": "saga-ltx25-gateway",
            "gatewayFunction": "web",
            "volume": "saga-ltx25-redgraft-cache",
            "stateDict": "saga-ltx25-redgraft-worker-state",
            "idleSeconds": 180,
            "maxConcurrency": 1,
        },
    ],
}
write("config/modal-worker-ecosystems.json", json.dumps(ECOSYSTEMS, indent=2) + "\n")
write(
    "apps/studio/api/_worker-registry.generated.js",
    "// Generated by the Modal worker provisioning workflow. Public routing metadata only; no credentials.\nexport const GENERATED_MODAL_WORKERS = [];\n",
)

WORKER_REGISTRY = r'''import { GENERATED_MODAL_WORKERS } from './_worker-registry.generated.js';

const CREDIT_PATTERNS = [
  'credit', 'credits', 'quota', 'budget', 'billing', 'payment', 'insufficient',
  'spending limit', 'spend limit', 'workspace budget', 'out of funds', 'balance',
];
const UNAVAILABLE_PATTERNS = [
  'workspace is disabled', 'workspace disabled', 'disabled workspace', 'not found',
  'unavailable', 'temporarily unavailable', 'connection refused', 'timed out', 'timeout',
  'container failed', 'app is stopped', 'app stopped',
];

function cleanText(value) {
  return String(value || '').trim();
}

function normalizeWorker(raw, index = 0) {
  if (!raw || typeof raw !== 'object') return null;
  const id = cleanText(raw.id || raw.workerId);
  const ecosystem = cleanText(raw.ecosystem || raw.ecosystemId);
  const gatewayUrl = cleanText(raw.gatewayUrl || raw.gateway_url).replace(/\/$/, '');
  if (!id || !ecosystem || !gatewayUrl) return null;
  return {
    id,
    ecosystem,
    gatewayUrl,
    displayName: cleanText(raw.displayName || raw.display_name) || ecosystem,
    accountLabel: cleanText(raw.accountLabel || raw.account || raw.account_label),
    role: cleanText(raw.role || 'primary').toLowerCase() === 'standby' ? 'standby' : 'primary',
    enabled: raw.enabled !== false,
    version: cleanText(raw.version || 'v1'),
    order: Number.isFinite(Number(raw.order)) ? Number(raw.order) : index,
  };
}

function envWorkers() {
  const raw = cleanText(process.env.SAGA_MODAL_WORKER_REGISTRY_JSON);
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    const rows = Array.isArray(parsed) ? parsed : Array.isArray(parsed?.workers) ? parsed.workers : [];
    return rows.map(normalizeWorker).filter(Boolean);
  } catch (error) {
    console.error('Invalid SAGA_MODAL_WORKER_REGISTRY_JSON', error);
    return [];
  }
}

function legacyWorker(workflow) {
  if (workflow?.provider === 'modal-flux2-klein') {
    return normalizeWorker({
      id: 'legacy-flux2-klein',
      ecosystem: workflow.ecosystem || 'flux2-klein-9b',
      displayName: 'FLUX.2 Klein 9B',
      gatewayUrl: process.env.FLUX2_KLEIN_GATEWAY_URL || 'https://faresmohamed260--saga-flux2-klein-gateway-web.modal.run',
      role: 'primary',
    });
  }
  if (workflow?.provider === 'modal-ltx25-redgraft') {
    return normalizeWorker({
      id: 'legacy-ltx25-redgraft',
      ecosystem: workflow.ecosystem || 'ltx25-redgraft',
      displayName: 'REDGraft LTX 2.5',
      gatewayUrl: process.env.LTX25_GATEWAY_URL || 'https://faresmohamed260--saga-ltx25-gateway-web.modal.run',
      role: 'primary',
    });
  }
  return null;
}

export function listConfiguredWorkers() {
  const merged = [...envWorkers(), ...(Array.isArray(GENERATED_MODAL_WORKERS) ? GENERATED_MODAL_WORKERS : [])]
    .map(normalizeWorker)
    .filter(Boolean);
  const unique = new Map();
  for (const worker of merged) if (!unique.has(worker.id)) unique.set(worker.id, worker);
  return [...unique.values()];
}

export function workersForWorkflow(workflow) {
  const ecosystem = cleanText(workflow?.ecosystem);
  const configured = listConfiguredWorkers()
    .filter((worker) => worker.enabled && worker.ecosystem === ecosystem)
    .sort((a, b) => {
      const role = (a.role === 'primary' ? 0 : 1) - (b.role === 'primary' ? 0 : 1);
      return role || a.order - b.order || a.id.localeCompare(b.id);
    });
  if (configured.length) return configured;
  const legacy = legacyWorker(workflow);
  return legacy ? [legacy] : [];
}

export function encodeProviderJobId(workerId, callId) {
  const payload = Buffer.from(JSON.stringify({ v: 1, workerId: cleanText(workerId), callId: cleanText(callId) }), 'utf8').toString('base64url');
  return `saga-worker:${payload}`;
}

export function decodeProviderJobId(providerJobId) {
  const raw = cleanText(providerJobId);
  if (!raw.startsWith('saga-worker:')) return { workerId: '', callId: raw, legacy: true };
  try {
    const payload = JSON.parse(Buffer.from(raw.slice('saga-worker:'.length), 'base64url').toString('utf8'));
    return { workerId: cleanText(payload?.workerId), callId: cleanText(payload?.callId), legacy: false };
  } catch {
    return { workerId: '', callId: raw, legacy: true };
  }
}

export function workerForProviderJob(workflow, providerJobId) {
  const decoded = decodeProviderJobId(providerJobId);
  if (decoded.legacy) return { worker: legacyWorker(workflow) || workersForWorkflow(workflow)[0] || null, callId: decoded.callId };
  const worker = listConfiguredWorkers().find((candidate) => candidate.id === decoded.workerId)
    || workersForWorkflow(workflow).find((candidate) => candidate.id === decoded.workerId)
    || null;
  return { worker, callId: decoded.callId };
}

function errorText({ body, error } = {}) {
  const pieces = [];
  if (body && typeof body === 'object') pieces.push(body.error, body.detail, body.errorCode, body.code, body.workerState);
  else pieces.push(body);
  if (error) pieces.push(error.message, error.name, error.cause?.message);
  return pieces.filter(Boolean).join(' ').toLowerCase();
}

export function classifyWorkerFailure({ status = 0, body = null, error = null } = {}) {
  const text = errorText({ body, error });
  if (Number(status) === 402 || CREDIT_PATTERNS.some((pattern) => text.includes(pattern))) {
    return { retryable: true, kind: 'credit_exhausted', code: 'WORKER_CREDIT_EXHAUSTED' };
  }
  if (Number(status) === 429 || Number(status) >= 500 || UNAVAILABLE_PATTERNS.some((pattern) => text.includes(pattern)) || error) {
    return { retryable: true, kind: 'unavailable', code: 'WORKER_UNAVAILABLE' };
  }
  return { retryable: false, kind: 'failed', code: 'PROVIDER_FAILED' };
}

export function providerFailureError(message, { status = 0, body = null, cause = null, worker = null } = {}) {
  const classification = classifyWorkerFailure({ status, body, error: cause });
  const error = new Error(message);
  error.statusCode = classification.retryable ? 503 : (Number(status) >= 400 ? Number(status) : 502);
  error.errorCode = classification.code;
  error.workerState = classification.kind;
  error.workerFailure = classification;
  error.workerId = worker?.id || '';
  error.ecosystem = worker?.ecosystem || '';
  if (cause) error.cause = cause;
  return error;
}

export async function submitWithWorkerFailover(workflow, operation) {
  const workers = workersForWorkflow(workflow);
  if (!workers.length) {
    const error = new Error(`No worker is configured for ${workflow?.ecosystem || workflow?.id || 'workflow'}`);
    error.statusCode = 503;
    error.errorCode = 'NO_WORKER_CONFIGURED';
    error.workerState = 'unavailable';
    throw error;
  }
  const failures = [];
  for (let index = 0; index < workers.length; index += 1) {
    const worker = workers[index];
    try {
      const result = await operation(worker, index);
      return { ...result, worker, failedWorkers: failures };
    } catch (error) {
      const failure = error?.workerFailure || classifyWorkerFailure({ error });
      failures.push({ workerId: worker.id, kind: failure.kind, code: failure.code });
      if (!failure.retryable) throw error;
      console.error('Modal worker failed; trying standby when available', {
        ecosystem: workflow?.ecosystem,
        workerId: worker.id,
        kind: failure.kind,
        code: failure.code,
      });
    }
  }
  const exhausted = failures.length > 0 && failures.every((failure) => failure.kind === 'credit_exhausted');
  const error = new Error(exhausted
    ? `All configured workers for ${workflow?.ecosystem || workflow?.id} have exhausted their available credits`
    : `No configured worker for ${workflow?.ecosystem || workflow?.id} is currently available`);
  error.statusCode = 503;
  error.errorCode = exhausted ? 'ALL_WORKERS_CREDIT_EXHAUSTED' : 'NO_WORKER_AVAILABLE';
  error.workerState = exhausted ? 'credit_exhausted' : 'unavailable';
  error.failures = failures;
  throw error;
}

export function publicWorkerStatus(worker, state = 'queued', extra = {}) {
  return {
    workerId: worker?.id || '',
    ecosystem: worker?.ecosystem || '',
    displayName: worker?.displayName || worker?.ecosystem || 'Generation worker',
    state: cleanText(state || 'queued') || 'queued',
    role: worker?.role || 'primary',
    ...extra,
  };
}
'''
write("apps/studio/api/_worker-registry.js", WORKER_REGISTRY)

# Workflow registry gains an ecosystem identifier independent from provider/account details.
replace_once(
    "apps/studio/api/_workflows.js",
    "    provider: 'modal-flux2-klein',\n",
    "    provider: 'modal-flux2-klein',\n    ecosystem: 'flux2-klein-9b',\n",
)
replace_once(
    "apps/studio/api/_workflows.js",
    "    provider: 'modal-ltx25-redgraft',\n",
    "    provider: 'modal-ltx25-redgraft',\n    ecosystem: 'ltx25-redgraft',\n",
)
replace_once(
    "apps/studio/api/_workflows.js",
    "    provider: workflow.provider,\n",
    "    provider: workflow.provider,\n    ecosystem: workflow.ecosystem,\n",
)

PROVIDERS = r'''import {
  encodeProviderJobId,
  providerFailureError,
  publicWorkerStatus,
  submitWithWorkerFailover,
  workerForProviderJob,
} from './_worker-registry.js';

function safeNumber(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function safeBoolean(value, fallback) {
  if (typeof value === 'boolean') return value;
  const text = String(value ?? '').trim().toLowerCase();
  if (['1', 'true', 'yes', 'on'].includes(text)) return true;
  if (['0', 'false', 'no', 'off'].includes(text)) return false;
  return fallback;
}

function normalizeAspectRatio(value, fallback = '16:9') {
  const text = String(value || fallback).trim();
  const match = text.match(/^(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)$/);
  if (!match) {
    const error = new Error(`Unsupported video aspect ratio: ${text || 'empty'}`);
    error.statusCode = 400;
    throw error;
  }
  const width = Number(match[1]);
  const height = Number(match[2]);
  const ratio = width / height;
  if (!Number.isFinite(ratio) || ratio < 0.4 || ratio > 2.5) {
    const error = new Error(`Video aspect ratio is outside the supported range: ${text}`);
    error.statusCode = 400;
    throw error;
  }
  return `${width}:${height}`;
}

function buildFluxForm(workflow, input) {
  const form = new FormData();
  input.sources.forEach((source, index) => {
    form.append('image_files', new Blob([source.bytes], { type: source.contentType || 'image/png' }), source.filename || `input-${index + 1}.png`);
  });
  form.append('prompt', input.prompt);
  form.append('negative_prompt', input.negativePrompt || workflow.defaults.negativePrompt);
  form.append('seed', String(input.seed));
  form.append('steps', String(input.steps));
  form.append('cfg', String(input.cfg));
  form.append('megapixels', String(input.megapixels));
  return form;
}

function buildLtx25Form(workflow, input) {
  const form = new FormData();
  const source = input.sources[0];
  if (source) form.append('image_file', new Blob([source.bytes], { type: source.contentType || 'image/png' }), source.filename || 'input.png');
  form.append('prompt', input.prompt);
  form.append('negative_prompt', input.negativePrompt || workflow.defaults.negativePrompt);
  form.append('seed', String(input.seed));
  form.append('resolution', input.resolution);
  form.append('duration_seconds', String(input.durationSeconds));
  form.append('audio_enabled', String(input.audioEnabled));
  form.append('aspect_ratio', input.aspectRatio);
  form.append('frame_rate', String(input.frameRate));
  return form;
}

function normalizeSources(workflow, rawInput) {
  const rawSources = Array.isArray(rawInput.sources) && rawInput.sources.length
    ? rawInput.sources
    : [{ bytes: rawInput.sourceBytes, contentType: rawInput.sourceContentType, filename: rawInput.sourceFilename }];
  const sources = rawSources.map((source, index) => {
    const bytes = Buffer.isBuffer(source?.bytes) ? source.bytes : Buffer.from(source?.bytes || []);
    if (bytes.length > workflow.limits.maxSourceBytes) {
      const error = new Error(`Reference Image ${index + 1} exceeds ${workflow.limits.maxSourceBytes} byte workflow limit`);
      error.statusCode = 413;
      throw error;
    }
    return { bytes, contentType: String(source?.contentType || 'image/png'), filename: String(source?.filename || `input-${index + 1}.png`).slice(0, 240) };
  }).filter((source) => source.bytes.length);
  if (workflow.requiresSourceImage && !sources.length) {
    const error = new Error('At least one reference image is required'); error.statusCode = 400; throw error;
  }
  if (!workflow.supportsMultipleReferences && sources.length > 1) {
    const error = new Error('This workflow accepts only one reference image'); error.statusCode = 400; throw error;
  }
  return sources;
}

function normalizeInput(workflow, rawInput) {
  if (!workflow) { const error = new Error('Unknown workflow'); error.statusCode = 404; throw error; }
  const sources = normalizeSources(workflow, rawInput);
  const prompt = String(rawInput.prompt || '').trim();
  if (!prompt) { const error = new Error('Prompt is required'); error.statusCode = 400; throw error; }
  const normalized = {
    sources,
    prompt: prompt.slice(0, 2400),
    negativePrompt: String(rawInput.negativePrompt || workflow.defaults.negativePrompt).slice(0, 2000),
    seed: Number.isSafeInteger(Number(rawInput.seed)) ? Number(rawInput.seed) : workflow.defaults.seed,
    steps: clamp(Math.round(safeNumber(rawInput.steps, workflow.defaults.steps)), 1, 50),
    cfg: safeNumber(rawInput.cfg, workflow.defaults.cfg),
    megapixels: clamp(safeNumber(rawInput.megapixels, workflow.defaults.megapixels), workflow.limits.minMegapixels, workflow.limits.maxMegapixels),
  };
  if (workflow.kind === 'video') {
    const allowedResolutions = workflow.limits.resolutions || [];
    const requestedResolution = String(rawInput.resolution || workflow.defaults.resolution || '').trim();
    if (!allowedResolutions.includes(requestedResolution)) { const error = new Error(`Unsupported video resolution: ${requestedResolution || 'empty'}`); error.statusCode = 400; throw error; }
    normalized.resolution = requestedResolution;
    normalized.durationSeconds = clamp(Math.round(safeNumber(rawInput.durationSeconds, workflow.defaults.durationSeconds)), workflow.limits.minDurationSeconds, workflow.limits.maxDurationSeconds);
    normalized.audioEnabled = safeBoolean(rawInput.audioEnabled, workflow.defaults.audioEnabled);
    normalized.aspectRatio = normalizeAspectRatio(rawInput.aspectRatio, workflow.defaults.aspectRatio);
    const requestedFrameRate = Math.round(safeNumber(rawInput.frameRate, workflow.defaults.frameRate));
    if (!(workflow.limits.frameRates || []).includes(requestedFrameRate)) { const error = new Error(`Unsupported video frame rate: ${requestedFrameRate}`); error.statusCode = 400; throw error; }
    normalized.frameRate = requestedFrameRate;
  }
  return normalized;
}

async function parseProviderError(response) {
  let body = {};
  try { body = await response.json(); } catch { body = {}; }
  const detail = body?.detail || body?.error || '';
  return { body, detail: detail ? `: ${detail}` : '' };
}

async function fetchWorker(worker, path, init) {
  try {
    return await fetch(`${worker.gatewayUrl}${path}`, init);
  } catch (cause) {
    throw providerFailureError(`Worker ${worker.id} could not be reached`, { cause, worker });
  }
}

async function responseFailure(response, worker, label) {
  const parsed = await parseProviderError(response);
  throw providerFailureError(`${label} (${response.status})${parsed.detail}`, { status: response.status, body: parsed.body, worker });
}

async function submitModalFlux2Klein(workflow, input) {
  const accepted = await submitWithWorkerFailover(workflow, async (worker) => {
    const response = await fetchWorker(worker, '/jobs/edit', { method: 'POST', body: buildFluxForm(workflow, input) });
    if (!response.ok) await responseFailure(response, worker, 'FLUX.2 provider submit failed');
    const payload = await response.json();
    if (!payload?.call_id) throw providerFailureError('FLUX.2 provider did not return a call id', { status: 502, body: payload, worker });
    return { callId: payload.call_id, state: payload.worker_state || payload.workerState || 'queued' };
  });
  return {
    providerJobId: encodeProviderJobId(accepted.worker.id, accepted.callId),
    provider: workflow.provider,
    status: 'queued',
    worker: publicWorkerStatus(accepted.worker, accepted.state, { failedWorkers: accepted.failedWorkers }),
  };
}

async function submitModalLtx25(workflow, input) {
  const accepted = await submitWithWorkerFailover(workflow, async (worker) => {
    const response = await fetchWorker(worker, '/jobs/video', { method: 'POST', body: buildLtx25Form(workflow, input) });
    if (!response.ok) await responseFailure(response, worker, 'REDGraft LTX 2.5 provider submit failed');
    const payload = await response.json();
    if (!payload?.call_id) throw providerFailureError('REDGraft LTX 2.5 provider did not return a call id', { status: 502, body: payload, worker });
    return { callId: payload.call_id, state: payload.worker_state || payload.workerState || 'queued' };
  });
  return {
    providerJobId: encodeProviderJobId(accepted.worker.id, accepted.callId),
    provider: workflow.provider,
    status: 'queued',
    worker: publicWorkerStatus(accepted.worker, accepted.state, { failedWorkers: accepted.failedWorkers }),
  };
}

async function pollWorkerJson(response) {
  try { return await response.json(); } catch { return {}; }
}

async function pollModalFlux2Klein(workflow, providerJobId) {
  const { worker, callId } = workerForProviderJob(workflow, providerJobId);
  if (!worker || !callId) throw providerFailureError('Assigned FLUX.2 worker is no longer configured', { worker });
  const response = await fetchWorker(worker, `/jobs/${encodeURIComponent(callId)}`, { method: 'GET', headers: { Accept: 'image/*, application/json' } });
  if (response.status === 202) {
    const payload = await pollWorkerJson(response);
    return { status: 'running', provider: workflow.provider, worker: publicWorkerStatus(worker, payload.worker_state || payload.workerState || 'generating') };
  }
  if (!response.ok) await responseFailure(response, worker, 'FLUX.2 provider poll failed');
  const contentType = String(response.headers.get('content-type') || workflow.outputMimeType).split(';')[0].trim();
  if (!contentType.startsWith('image/')) { const error = new Error('Generation provider returned a non-image response'); error.statusCode = 502; throw error; }
  return { status: 'completed', bytes: Buffer.from(await response.arrayBuffer()), contentType, provider: workflow.provider, worker: publicWorkerStatus(worker, 'finalizing') };
}

async function pollModalLtx25(workflow, providerJobId) {
  const { worker, callId } = workerForProviderJob(workflow, providerJobId);
  if (!worker || !callId) throw providerFailureError('Assigned REDGraft LTX 2.5 worker is no longer configured', { worker });
  const encodedJobId = encodeURIComponent(callId);
  const response = await fetchWorker(worker, `/jobs/${encodedJobId}`, { method: 'GET', headers: { Accept: 'video/*, application/json' } });
  if (response.status === 202) {
    const payload = await pollWorkerJson(response);
    return { status: 'running', provider: workflow.provider, worker: publicWorkerStatus(worker, payload.worker_state || payload.workerState || 'generating') };
  }
  if (!response.ok) await responseFailure(response, worker, 'REDGraft LTX 2.5 provider poll failed');
  const contentType = String(response.headers.get('content-type') || workflow.outputMimeType).split(';')[0].trim();
  if (!contentType.startsWith('video/')) { const error = new Error('Generation provider returned a non-video response'); error.statusCode = 502; throw error; }
  const bytes = Buffer.from(await response.arrayBuffer());
  let posterBytes = null;
  let posterContentType = null;
  try {
    const posterResponse = await fetchWorker(worker, `/jobs/${encodedJobId}/poster`, { method: 'GET', headers: { Accept: 'image/*, application/json' } });
    if (posterResponse.ok) {
      const candidateType = String(posterResponse.headers.get('content-type') || '').split(';')[0].trim();
      if (candidateType.startsWith('image/')) { posterBytes = Buffer.from(await posterResponse.arrayBuffer()); posterContentType = candidateType; }
    } else if (![202, 404, 410].includes(posterResponse.status)) console.error(`REDGraft LTX 2.5 poster fetch failed (${posterResponse.status})`);
  } catch (error) { console.error('REDGraft LTX 2.5 poster fetch failed', error); }
  return { status: 'completed', bytes, contentType, posterBytes, posterContentType, provider: workflow.provider, worker: publicWorkerStatus(worker, 'finalizing') };
}

async function cancelProviderJob(worker, providerLabel, workflow, callId) {
  const response = await fetchWorker(worker, `/jobs/${encodeURIComponent(callId)}`, { method: 'DELETE', headers: { Accept: 'application/json' } });
  if (!response.ok) await responseFailure(response, worker, `${providerLabel} provider cancel failed`);
  return { status: 'cancelled', provider: workflow.provider, worker: publicWorkerStatus(worker, 'ready') };
}

export async function submitWorkflow(workflow, rawInput) {
  const normalized = normalizeInput(workflow, rawInput);
  if (workflow.provider === 'modal-flux2-klein') return submitModalFlux2Klein(workflow, normalized);
  if (workflow.provider === 'modal-ltx25-redgraft') return submitModalLtx25(workflow, normalized);
  const error = new Error(`Unsupported provider: ${workflow.provider}`); error.statusCode = 501; throw error;
}

export async function pollWorkflow(workflow, providerJobId) {
  if (!workflow) { const error = new Error('Unknown workflow'); error.statusCode = 404; throw error; }
  if (!providerJobId) { const error = new Error('Provider job id is required'); error.statusCode = 400; throw error; }
  if (workflow.provider === 'modal-flux2-klein') return pollModalFlux2Klein(workflow, providerJobId);
  if (workflow.provider === 'modal-ltx25-redgraft') return pollModalLtx25(workflow, providerJobId);
  const error = new Error(`Unsupported provider: ${workflow.provider}`); error.statusCode = 501; throw error;
}

export async function cancelWorkflow(workflow, providerJobId) {
  if (!workflow) { const error = new Error('Unknown workflow'); error.statusCode = 404; throw error; }
  if (!providerJobId) return { status: 'cancelled', provider: workflow.provider };
  const { worker, callId } = workerForProviderJob(workflow, providerJobId);
  if (!worker || !callId) throw providerFailureError('Assigned worker is no longer configured', { worker });
  if (workflow.provider === 'modal-flux2-klein') return cancelProviderJob(worker, 'FLUX.2', workflow, callId);
  if (workflow.provider === 'modal-ltx25-redgraft') return cancelProviderJob(worker, 'REDGraft LTX 2.5', workflow, callId);
  const error = new Error(`Unsupported provider: ${workflow.provider}`); error.statusCode = 501; throw error;
}
'''
write("apps/studio/api/_providers.js", PROVIDERS)

# Expose ecosystem/worker information from submit and poll without changing DB schema.
replace_once(
    "apps/studio/api/generate.js",
    "        inputTransport,\n",
    "        inputTransport,\n        ecosystem: workflow.ecosystem || null,\n",
)
replace_once(
    "apps/studio/api/generate.js",
    """      provider: workflow.provider,\n      inputTransport,\n      referenceCount: sources.length,\n""",
    """      provider: workflow.provider,\n      ecosystem: workflow.ecosystem || null,\n      worker: submitted.worker || null,\n      inputTransport,\n      referenceCount: sources.length,\n""",
)
replace_once(
    "apps/studio/api/generate.js",
    "return res.status(error?.statusCode || 500).json({ error: error?.message || 'Generation submit failed' });",
    "return res.status(error?.statusCode || 500).json({ error: error?.message || 'Generation submit failed', errorCode: error?.errorCode || null, workerState: error?.workerState || null });",
)

replace_once(
    "apps/studio/api/generate/result.js",
    "if (!job.workflow_id || !job.provider_job_id) return res.status(202).json({ status: job.status || 'queued' });",
    "if (!job.workflow_id || !job.provider_job_id) return res.status(202).json({ status: job.status || 'queued', workerState: 'queued', ecosystem: job.metadata?.ecosystem || null });",
)
replace_once(
    "apps/studio/api/generate/result.js",
    "if (result.status !== 'completed') return res.status(202).json({ status: 'running' });",
    "if (result.status !== 'completed') return res.status(202).json({ status: 'running', workerState: result.worker?.state || 'generating', worker: result.worker || null, ecosystem: workflow.ecosystem || null });",
)
replace_once(
    "apps/studio/api/generate/result.js",
    "return res.status(error?.statusCode || 500).json({ error: error?.message || 'Generation result poll failed' });",
    "return res.status(error?.statusCode || 500).json({ error: error?.message || 'Generation result poll failed', errorCode: error?.errorCode || null, workerState: error?.workerState || null });",
)

# Client keeps legacy phase callbacks while adding a separate real worker-status channel.
generation_client = read("apps/studio/src/generation-client.js")
generation_client = generation_client.replace(
    "return payload.job;",
    "return { job: payload.job, worker: payload.worker || null };",
    2,
)
generation_client = generation_client.replace(
    """    if (onStatus) onStatus('running');\n    const response = await fetch(`/api/generate/result?jobId=${encodeURIComponent(jobId)}`, {\n""",
    """    if (onStatus) onStatus('running');\n    const response = await fetch(`/api/generate/result?jobId=${encodeURIComponent(jobId)}`, {\n""",
    1,
)
generation_client = generation_client.replace(
    """    if (response.status === 202) {\n      await sleep(intervalMs);\n      continue;\n    }\n""",
    """    if (response.status === 202) {\n      const pending = await response.json().catch(() => ({}));\n      if (onWorkerStatus) onWorkerStatus(pending.worker || { state: pending.workerState || 'queued', ecosystem: pending.ecosystem || '' });\n      await sleep(intervalMs);\n      continue;\n    }\n""",
    1,
)
generation_client = generation_client.replace(
    "export async function waitForGeneration(jobId, { intervalMs = 2000, timeoutMs = 30 * 60 * 1000, onStatus } = {}) {",
    "export async function waitForGeneration(jobId, { intervalMs = 2000, timeoutMs = 30 * 60 * 1000, onStatus, onWorkerStatus } = {}) {",
    1,
)
generation_client = generation_client.replace(
    """  const job = await submitImageEdit(effectiveInput);\n  if (options.onStatus) options.onStatus('running');\n  const result = await waitForGeneration(job.id, options);\n  return { job, result };\n""",
    """  const submitted = await submitImageEdit(effectiveInput);\n  if (options.onWorkerStatus && submitted.worker) options.onWorkerStatus(submitted.worker);\n  if (options.onStatus) options.onStatus('running');\n  const result = await waitForGeneration(submitted.job.id, options);\n  return { job: submitted.job, result };\n""",
    1,
)
generation_client = generation_client.replace(
    """  const job = await submitVideoGeneration(input);\n  if (options.onStatus) options.onStatus('running');\n  const result = await waitForGeneration(job.id, {\n""",
    """  const submitted = await submitVideoGeneration(input);\n  if (options.onWorkerStatus && submitted.worker) options.onWorkerStatus(submitted.worker);\n  if (options.onStatus) options.onStatus('running');\n  const result = await waitForGeneration(submitted.job.id, {\n""",
    1,
)
generation_client = generation_client.replace(
    """  return { job, result };\n}\n""",
    """  return { job: submitted.job, result };\n}\n""",
    1,
)
write("apps/studio/src/generation-client.js", generation_client)

# App stores worker status independently of generic job phase.
replace_once(
    "apps/studio/src/app/App.jsx",
    "  const [jobStatus, setJobStatus] = useState('');\n",
    "  const [jobStatus, setJobStatus] = useState('');\n  const [workerStatus, setWorkerStatus] = useState(null);\n",
)
app = read("apps/studio/src/app/App.jsx")
app = app.replace("}, { onStatus: setJobStatus });", "}, { onStatus: setJobStatus, onWorkerStatus: setWorkerStatus });", 2)
app = app.replace("setBusy(true); setError(''); setJobStatus('');", "setBusy(true); setError(''); setJobStatus(''); setWorkerStatus(null);", 1)
app = app.replace("      setJobStatus('failed');\n      setError(", "      setJobStatus('failed');\n      setWorkerStatus((current) => ({ ...(current || {}), state: 'failed' }));\n      setError(", 1)
app = app.replace("error={error} jobStatus={jobStatus} busy={busy}", "error={error} jobStatus={jobStatus} workerStatus={workerStatus} busy={busy}", 1)
write("apps/studio/src/app/App.jsx", app)

# Create workspace exposes the worker indicator for both Edit and Video ecosystems.
replace_once(
    "apps/studio/src/features/create/CreateWorkspace.jsx",
    "  const { mode, references = [], busy, jobStatus, onGenerate } = props;",
    "  const { mode, references = [], busy, jobStatus, workerStatus, onGenerate } = props;",
)
replace_once(
    "apps/studio/src/features/create/CreateWorkspace.jsx",
    """    if (mode !== 'Video') {\n      setToolbarHost(null);\n      setComposerHost(null);\n      return;\n    }\n    const frame = window.requestAnimationFrame(() => {\n      setToolbarHost(document.querySelector('.saga-composer.is-video .saga-toolbar-left'));\n      setComposerHost(document.querySelector('.saga-composer.is-video'));\n    });\n""",
    """    if (mode !== 'Video' && mode !== 'Edit') {\n      setToolbarHost(null);\n      setComposerHost(null);\n      return;\n    }\n    const frame = window.requestAnimationFrame(() => {\n      setToolbarHost(mode === 'Video' ? document.querySelector('.saga-composer.is-video .saga-toolbar-left') : null);\n      setComposerHost(document.querySelector(mode === 'Video' ? '.saga-composer.is-video' : '.saga-composer.is-edit'));\n    });\n""",
)
replace_once(
    "apps/studio/src/features/create/CreateWorkspace.jsx",
    """      {mode === 'Video' && composerHost && createPortal(\n        <VideoGenerationProgress busy={busy} status={jobStatus} />,\n        composerHost,\n      )}\n""",
    """      {(mode === 'Video' || mode === 'Edit') && composerHost && createPortal(\n        <VideoGenerationProgress busy={busy} status={jobStatus} workerStatus={workerStatus} kind={mode === 'Video' ? 'video' : 'image'} />,\n        composerHost,\n      )}\n""",
)

# Replace progress copy with real worker lifecycle states, while retaining legacy fallback phases.
controls = read("apps/studio/src/features/create/VideoGenerationControls.jsx")
start = controls.index("const STATUS_COPY = {")
end = controls.index("\nexport function VideoGenerationProgress", start)
new_status = r'''const STATUS_COPY = {
  uploading: ['Uploading reference', 'Preparing the source image for generation.'],
  submitting: ['Submitting generation', 'Sending the request to the assigned model ecosystem.'],
  queued: ['Waiting for worker', 'The request is queued for an available ecosystem worker.'],
  sleeping: ['Worker sleeping', 'Compute is scaled to zero and will start on demand.'],
  waking: ['Starting worker', 'The assigned worker is waking from zero compute.'],
  loading: ['Loading model', 'Cached model assets are loading into GPU memory.'],
  ready: ['Worker ready', 'The model ecosystem is ready to begin generation.'],
  generating: ['Generating', 'The assigned model ecosystem is producing the requested media.'],
  running: ['Generating', 'The assigned model ecosystem is producing the requested media.'],
  finalizing: ['Finalizing result', 'Generation is complete and the result is being prepared for Gallery.'],
  credit_exhausted: ['Switching worker', 'The assigned worker reached its credit limit. A standby worker will be used when available.'],
  unavailable: ['Worker unavailable', 'The assigned worker is unavailable. A standby worker will be used when available.'],
  completed: ['Generation ready', 'The completed result has been saved to Gallery.'],
  failed: ['Generation failed', 'The request did not complete. See the message below for details.'],
};
'''
controls = controls[:start] + new_status + controls[end:]
controls = controls.replace("export function VideoGenerationProgress({ busy, status }) {", "export function VideoGenerationProgress({ busy, status, workerStatus, kind = 'video' }) {")
controls = controls.replace("  const normalized = status || (busy ? 'submitting' : 'completed');\n  const [title, detail] = STATUS_COPY[normalized] || STATUS_COPY.running;", "  const normalized = workerStatus?.state || status || (busy ? 'submitting' : 'completed');\n  const [baseTitle, baseDetail] = STATUS_COPY[normalized] || STATUS_COPY.running;\n  const title = normalized === 'generating' || normalized === 'running' ? `Generating ${kind}` : baseTitle;\n  const workerName = workerStatus?.displayName || '';\n  const detail = workerName ? `${baseDetail} · ${workerName}` : baseDetail;")
write("apps/studio/src/features/create/VideoGenerationControls.jsx", controls)

# Runtime: ecosystem-specific persistent volumes, scale-to-zero, and durable real worker state.
flux = read("integrations/comfyui/flux2_klein_app.py")
flux = flux.replace('WORKER_MIN_CONTAINERS = int(os.environ.get("MODAL_FLUX2_KLEIN_MIN_CONTAINERS", "0"))', 'WORKER_MIN_CONTAINERS = 0\nWORKER_MAX_CONTAINERS = int(os.environ.get("MODAL_FLUX2_KLEIN_MAX_CONTAINERS", "1"))\nECOSYSTEM_ID = "flux2-klein-9b"\nWORKER_ID = os.environ.get("SAGA_MODAL_WORKER_ID", f"{ECOSYSTEM_ID}-worker")\nSTATE_DICT_NAME = os.environ.get("SAGA_MODAL_WORKER_STATE_DICT", "saga-flux2-klein-9b-worker-state")\nCACHE_VOLUME_NAME = os.environ.get("SAGA_MODAL_WORKER_VOLUME", "saga-flux2-klein-9b-cache")')
flux = flux.replace('cache_volume = modal.Volume.from_name("graduation-comfyui-cache", create_if_missing=True)', 'cache_volume = modal.Volume.from_name(CACHE_VOLUME_NAME, create_if_missing=True)\nworker_state = modal.Dict.from_name(STATE_DICT_NAME, create_if_missing=True)')
flux = flux.replace('def _log(event: str, **fields: Any) -> None:\n    print({"event": event, **fields}, flush=True)\n', 'def _log(event: str, **fields: Any) -> None:\n    print({"event": event, **fields}, flush=True)\n\n\ndef _set_worker_state(state: str, **fields: Any) -> None:\n    payload = {"state": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID, "updated_at": int(time.time()), **fields}\n    worker_state["worker"] = payload\n    _log("worker_state", **payload)\n')
flux = flux.replace('    files = _ensure_model_files(force_checkpoint=force_checkpoint)\n    return {', '    files = _ensure_model_files(force_checkpoint=force_checkpoint)\n    _set_worker_state("sleeping", assets_cached=True)\n    return {', 1)
flux = flux.replace('    min_containers=WORKER_MIN_CONTAINERS,\n    volumes={CACHE_DIR: cache_volume},', '    min_containers=WORKER_MIN_CONTAINERS,\n    max_containers=WORKER_MAX_CONTAINERS,\n    volumes={CACHE_DIR: cache_volume},')
flux = flux.replace('    def start(self) -> None:\n        started = time.perf_counter()', '    def start(self) -> None:\n        _set_worker_state("loading")\n        started = time.perf_counter()', 1)
flux = flux.replace('        _log("flux2_klein_worker_ready", **self._status)', '        _set_worker_state("ready", startup_seconds=self._status["startup_seconds"])\n        _log("flux2_klein_worker_ready", **self._status)', 1)
flux = flux.replace('        started = time.perf_counter()\n        result = self._queue_and_wait(workflow, prompt_id)', '        _set_worker_state("generating", job_token=prompt_id[:12])\n        started = time.perf_counter()\n        try:\n            result = self._queue_and_wait(workflow, prompt_id)\n            _set_worker_state("finalizing", job_token=prompt_id[:12])\n        except Exception:\n            _set_worker_state("failed", job_token=prompt_id[:12])\n            raise', 1)
flux = flux.replace('        return result\n\n\n@app.function', '        _set_worker_state("ready")\n        return result\n\n    @modal.exit()\n    def stop(self) -> None:\n        _set_worker_state("sleeping")\n\n\n@app.function', 1)
write("integrations/comfyui/flux2_klein_app.py", flux)

ltx = read("integrations/comfyui/ltx23_app.py")
ltx = ltx.replace('GPU_TYPE = os.environ.get("MODAL_LTX25_GPU", "A10")', 'GPU_TYPE = os.environ.get("MODAL_LTX25_GPU", "A10")\nCONTAINER_IDLE_SECONDS = int(os.environ.get("MODAL_LTX25_IDLE_SECONDS", "180"))\nWORKER_MIN_CONTAINERS = 0\nWORKER_MAX_CONTAINERS = int(os.environ.get("MODAL_LTX25_MAX_CONTAINERS", "1"))\nECOSYSTEM_ID = "ltx25-redgraft"\nWORKER_ID = os.environ.get("SAGA_MODAL_WORKER_ID", f"{ECOSYSTEM_ID}-worker")\nSTATE_DICT_NAME = os.environ.get("SAGA_MODAL_WORKER_STATE_DICT", "saga-ltx25-redgraft-worker-state")\nCACHE_VOLUME_NAME = os.environ.get("SAGA_MODAL_WORKER_VOLUME", "saga-ltx25-redgraft-cache")')
ltx = ltx.replace('cache_volume = modal.Volume.from_name("graduation-comfyui-cache", create_if_missing=True)', 'cache_volume = modal.Volume.from_name(CACHE_VOLUME_NAME, create_if_missing=True)\nworker_state = modal.Dict.from_name(STATE_DICT_NAME, create_if_missing=True)')
ltx = ltx.replace('def _log(event: str, **fields: Any) -> None:\n    print({"event": event, **fields}, flush=True)\n', 'def _log(event: str, **fields: Any) -> None:\n    print({"event": event, **fields}, flush=True)\n\n\ndef _set_worker_state(state: str, **fields: Any) -> None:\n    payload = {"state": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID, "updated_at": int(time.time()), **fields}\n    worker_state["worker"] = payload\n    _log("worker_state", **payload)\n')
ltx = ltx.replace('    files = _ensure_model_files(verify_checkpoint=verify_checkpoint)\n    return {', '    files = _ensure_model_files(verify_checkpoint=verify_checkpoint)\n    _set_worker_state("sleeping", assets_cached=True)\n    return {', 1)
ltx = ltx.replace('    scaledown_window=300,', '    scaledown_window=CONTAINER_IDLE_SECONDS,\n    min_containers=WORKER_MIN_CONTAINERS,\n    max_containers=WORKER_MAX_CONTAINERS,', 1)
ltx = ltx.replace('    def start(self) -> None:\n        started = time.perf_counter()', '    def start(self) -> None:\n        _set_worker_state("loading")\n        started = time.perf_counter()', 1)
ltx = ltx.replace('        self.started_seconds = round(time.perf_counter() - started, 3)', '        self.started_seconds = round(time.perf_counter() - started, 3)\n        _set_worker_state("ready", startup_seconds=self.started_seconds)', 1)
ltx = ltx.replace('        source_name = _upload_image(source_image) if source_image else None', '        _set_worker_state("generating")\n        source_name = _upload_image(source_image) if source_image else None', 1)
ltx = ltx.replace('                    _log(\n                        "ltx25_delivery_ready",', '                    _set_worker_state("finalizing")\n                    _log(\n                        "ltx25_delivery_ready",', 1)
ltx = ltx.replace('                    return final_path.read_bytes()', '                    result = final_path.read_bytes()\n                    _set_worker_state("ready")\n                    return result', 1)
ltx = ltx.replace('        raise TimeoutError("REDGraft LTX 2.5 generation timed out")', '        _set_worker_state("failed")\n        raise TimeoutError("REDGraft LTX 2.5 generation timed out")\n\n    @modal.exit()\n    def stop(self) -> None:\n        _set_worker_state("sleeping")', 1)
write("integrations/comfyui/ltx23_app.py", ltx)

# Gateways report state without waking GPU and normalize credit/unavailable errors.
GATEWAY_HELPERS = r'''
CREDIT_PATTERNS = ("credit", "credits", "quota", "budget", "billing", "payment", "insufficient", "spending limit", "workspace budget")
UNAVAILABLE_PATTERNS = ("workspace is disabled", "workspace disabled", "unavailable", "not found", "stopped")


def _failure_payload(exc):
    text = f"{type(exc).__name__}: {exc}"
    lowered = text.lower()
    if any(pattern in lowered for pattern in CREDIT_PATTERNS):
        return 402, "WORKER_CREDIT_EXHAUSTED", "credit_exhausted", text
    if any(pattern in lowered for pattern in UNAVAILABLE_PATTERNS):
        return 503, "WORKER_UNAVAILABLE", "unavailable", text
    return 502, "WORKER_RUNTIME_FAILED", "failed", text
'''

flux_gateway = read("integrations/comfyui/flux2_klein_gateway.py")
flux_gateway = flux_gateway.replace('MODAL_VERSION = "1.4.2"', 'MODAL_VERSION = "1.4.2"\nECOSYSTEM_ID = "flux2-klein-9b"\nWORKER_ID = os.environ.get("SAGA_MODAL_WORKER_ID", f"{ECOSYSTEM_ID}-worker")\nSTATE_DICT_NAME = os.environ.get("SAGA_MODAL_WORKER_STATE_DICT", "saga-flux2-klein-9b-worker-state")\nworker_state = modal.Dict.from_name(STATE_DICT_NAME, create_if_missing=True)')
flux_gateway = flux_gateway.replace('image = modal.Image', GATEWAY_HELPERS + '\nimage = modal.Image', 1)
flux_gateway = flux_gateway.replace('    @api.get("/health")\n    async def health():\n        return {', '    def _state():\n        try:\n            return worker_state.get("worker") or {"state": "sleeping", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID}\n        except Exception:\n            return {"state": "unknown", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID}\n\n    @api.get("/health")\n    async def health():\n        return {', 1)
flux_gateway = flux_gateway.replace('            "multiple_references": True,\n        }', '            "multiple_references": True,\n            "worker": _state(),\n        }', 1)
flux_gateway = flux_gateway.replace('            return {"status": "queued", "call_id": call.object_id, "reference_count": len(images)}', '            current = _state()\n            return {"status": "queued", "call_id": call.object_id, "reference_count": len(images), "worker_state": current.get("state") or "waking", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID}', 1)
flux_gateway = flux_gateway.replace('            raise HTTPException(status_code=502, detail=f"FLUX.2 runtime submit failed: {type(exc).__name__}: {exc}") from exc', '            status_code, error_code, state, detail = _failure_payload(exc)\n            return JSONResponse(status_code=status_code, content={"error": detail, "errorCode": error_code, "workerState": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
flux_gateway = flux_gateway.replace('            return JSONResponse(status_code=202, content={"status": "running", "call_id": call_id})', '            current = _state()\n            return JSONResponse(status_code=202, content={"status": "running", "call_id": call_id, "worker_state": current.get("state") or "generating", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
flux_gateway = flux_gateway.replace('            raise HTTPException(status_code=502, detail=f"FLUX.2 runtime failed: {type(exc).__name__}: {exc}") from exc', '            status_code, error_code, state, detail = _failure_payload(exc)\n            return JSONResponse(status_code=status_code, content={"error": detail, "errorCode": error_code, "workerState": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
write("integrations/comfyui/flux2_klein_gateway.py", flux_gateway)

ltx_gateway = read("integrations/comfyui/ltx23_gateway.py")
ltx_gateway = ltx_gateway.replace('MODAL_VERSION = "1.4.2"', 'MODAL_VERSION = "1.4.2"\nECOSYSTEM_ID = "ltx25-redgraft"\nWORKER_ID = os.environ.get("SAGA_MODAL_WORKER_ID", f"{ECOSYSTEM_ID}-worker")\nSTATE_DICT_NAME = os.environ.get("SAGA_MODAL_WORKER_STATE_DICT", "saga-ltx25-redgraft-worker-state")\nworker_state = modal.Dict.from_name(STATE_DICT_NAME, create_if_missing=True)')
ltx_gateway = ltx_gateway.replace('image = modal.Image', GATEWAY_HELPERS + '\nimage = modal.Image', 1)
ltx_gateway = ltx_gateway.replace('    def _worker():\n        return modal.Cls.from_name(RUNTIME_APP_NAME, RUNTIME_CLASS_NAME)()\n', '    def _worker():\n        return modal.Cls.from_name(RUNTIME_APP_NAME, RUNTIME_CLASS_NAME)()\n\n    def _state():\n        try:\n            return worker_state.get("worker") or {"state": "sleeping", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID}\n        except Exception:\n            return {"state": "unknown", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID}\n')
old_health = '''    @api.get("/health")\n    async def health():\n        try:\n            runtime = _worker().health.remote()\n        except Exception as exc:  # noqa: BLE001\n            raise HTTPException(status_code=502, detail=f"LTX 2.5 runtime health failed: {type(exc).__name__}: {exc}") from exc\n        return {\n            "ready": bool(runtime.get("ready")),\n            "gateway": APP_NAME,\n            "runtime_app": RUNTIME_APP_NAME,\n            "runtime_class": RUNTIME_CLASS_NAME,\n            "async_jobs": True,\n            "cancel_jobs": True,\n            "runtime": runtime,\n        }\n'''
new_health = '''    @api.get("/health")\n    async def health():\n        return {\n            "ready": True,\n            "gateway": APP_NAME,\n            "runtime_app": RUNTIME_APP_NAME,\n            "runtime_class": RUNTIME_CLASS_NAME,\n            "async_jobs": True,\n            "cancel_jobs": True,\n            "worker": _state(),\n        }\n'''
if old_health not in ltx_gateway:
    raise SystemExit('LTX health patch anchor missing')
ltx_gateway = ltx_gateway.replace(old_health, new_health, 1)
ltx_gateway = ltx_gateway.replace('                "frame_rate": normalized_frame_rate,\n            }', '                "frame_rate": normalized_frame_rate,\n                "worker_state": (_state().get("state") or "waking"),\n                "worker_id": WORKER_ID,\n                "ecosystem": ECOSYSTEM_ID,\n            }', 1)
ltx_gateway = ltx_gateway.replace('            raise HTTPException(status_code=502, detail=f"LTX 2.5 runtime submit failed: {type(exc).__name__}: {exc}") from exc', '            status_code, error_code, state, detail = _failure_payload(exc)\n            return JSONResponse(status_code=status_code, content={"error": detail, "errorCode": error_code, "workerState": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
ltx_gateway = ltx_gateway.replace('            return JSONResponse(status_code=202, content={"status": "running", "call_id": call_id})', '            current = _state()\n            return JSONResponse(status_code=202, content={"status": "running", "call_id": call_id, "worker_state": current.get("state") or "generating", "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
ltx_gateway = ltx_gateway.replace('            raise HTTPException(status_code=502, detail=f"LTX 2.5 runtime failed: {type(exc).__name__}: {exc}") from exc', '            status_code, error_code, state, detail = _failure_payload(exc)\n            return JSONResponse(status_code=status_code, content={"error": detail, "errorCode": error_code, "workerState": state, "worker_id": WORKER_ID, "ecosystem": ECOSYSTEM_ID})', 1)
write("integrations/comfyui/ltx23_gateway.py", ltx_gateway)

# Deterministic worker routing/credit-failover contract.
WORKER_TEST = r'''import assert from 'node:assert/strict';
import { classifyWorkerFailure, decodeProviderJobId, encodeProviderJobId, workersForWorkflow } from '../api/_worker-registry.js';
import { getWorkflow } from '../api/_workflows.js';

process.env.SAGA_MODAL_WORKER_REGISTRY_JSON = JSON.stringify({ workers: [
  { id: 'flux-primary', ecosystem: 'flux2-klein-9b', gatewayUrl: 'https://primary.example', role: 'primary', enabled: true },
  { id: 'flux-standby', ecosystem: 'flux2-klein-9b', gatewayUrl: 'https://standby.example', role: 'standby', enabled: true },
  { id: 'ltx-primary', ecosystem: 'ltx25-redgraft', gatewayUrl: 'https://ltx.example', role: 'primary', enabled: true },
] });

const flux = getWorkflow('flux2-klein-image-edit');
const ltx = getWorkflow('ltx25-redgraft-video');
assert.equal(flux.ecosystem, 'flux2-klein-9b');
assert.equal(ltx.ecosystem, 'ltx25-redgraft');
assert.deepEqual(workersForWorkflow(flux).map((worker) => worker.id), ['flux-primary', 'flux-standby']);
assert.deepEqual(workersForWorkflow(ltx).map((worker) => worker.id), ['ltx-primary']);

const encoded = encodeProviderJobId('flux-standby', 'fc-123');
assert.deepEqual(decodeProviderJobId(encoded), { workerId: 'flux-standby', callId: 'fc-123', legacy: false });
assert.equal(decodeProviderJobId('fc-legacy').legacy, true);

assert.equal(classifyWorkerFailure({ status: 402, body: { detail: 'insufficient credits' } }).kind, 'credit_exhausted');
assert.equal(classifyWorkerFailure({ status: 503, body: { detail: 'workspace is disabled' } }).kind, 'unavailable');
assert.equal(classifyWorkerFailure({ status: 400, body: { detail: 'prompt is required' } }).retryable, false);
console.log('Modal worker registry contract passed: ecosystem affinity, primary/standby ordering, pinned provider IDs, and credit/unavailable classification.');
'''
write("apps/studio/scripts/check-worker-registry-contract.mjs", WORKER_TEST)

package = json.loads(read("apps/studio/package.json"))
if "check-worker-registry-contract.mjs" not in package["scripts"]["build"]:
    package["scripts"]["build"] = package["scripts"]["build"].replace("node scripts/check-workflow-contract.mjs", "node scripts/check-workflow-contract.mjs && node scripts/check-worker-registry-contract.mjs")
write("apps/studio/package.json", json.dumps(package, indent=2) + "\n")

# Fleet inventory/provisioning utility. It never prints credentials.
FLEET = r'''#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CREDIT_WORDS = ("credit", "credits", "quota", "budget", "billing", "payment", "insufficient", "spending limit", "workspace budget")
DISABLED_WORDS = ("workspace is disabled", "workspace disabled", "disabled workspace")

@dataclass(frozen=True)
class Account:
    label: str
    token_id: str
    token_secret: str


def load_accounts() -> list[Account]:
    raw = os.environ.get("SAGA_MODAL_TOKENS_JSON", "").strip()
    if not raw:
        raise SystemExit("SAGA_MODAL_TOKENS_JSON is not configured")
    payload = json.loads(raw)
    rows = payload.get("accounts") or payload.get("tokens") or payload.get("roster") or [] if isinstance(payload, dict) else payload
    if not isinstance(rows, list):
        raise SystemExit("Modal roster must be a list")
    accounts: list[Account] = []
    for index, row in enumerate(rows, start=1):
        if not isinstance(row, dict):
            continue
        label = str(row.get("label") or row.get("name") or row.get("account") or f"modal-{index:02d}").strip()
        token_id = str(row.get("token_id") or "").strip()
        token_secret = str(row.get("token_secret") or "").strip()
        combined = str(row.get("api_key") or row.get("token") or "").strip()
        if (not token_id or not token_secret) and "." in combined:
            token_id, token_secret = combined.split(".", 1)
        if token_id and token_secret:
            accounts.append(Account(label, token_id, token_secret))
    return accounts


def env_for(account: Account, extra: dict[str, str] | None = None) -> dict[str, str]:
    env = dict(os.environ)
    env["MODAL_TOKEN_ID"] = account.token_id
    env["MODAL_TOKEN_SECRET"] = account.token_secret
    if extra:
        env.update({key: str(value) for key, value in extra.items()})
    return env


def run(account: Account, args: list[str], *, check: bool = False, extra: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=ROOT, env=env_for(account, extra), text=True, capture_output=True, check=check)


def json_command(account: Account, args: list[str]) -> tuple[Any, str]:
    result = run(account, args)
    output = (result.stdout or "").strip()
    detail = ((result.stderr or "") + " " + output).strip()
    if result.returncode != 0:
        return None, detail
    try:
        return json.loads(output or "null"), detail
    except json.JSONDecodeError:
        return None, detail


def classify(detail: str) -> str:
    text = str(detail or "").lower()
    if any(word in text for word in DISABLED_WORDS):
        return "disabled"
    if any(word in text for word in CREDIT_WORDS):
        return "credit_exhausted"
    return "error"


def inventory_account(account: Account) -> dict[str, Any]:
    apps, apps_detail = json_command(account, ["modal", "app", "list", "--json"])
    if apps is None:
        return {"account": account.label, "state": classify(apps_detail), "detail": apps_detail[-500:]}
    volumes, volumes_detail = json_command(account, ["modal", "volume", "list", "--json"])
    if volumes is None:
        return {"account": account.label, "state": classify(volumes_detail), "detail": volumes_detail[-500:]}
    billing, billing_detail = json_command(account, ["modal", "billing", "summary", "--json"])
    state = "available" if billing is not None else classify(billing_detail)
    return {
        "account": account.label,
        "state": state,
        "apps": len(apps) if isinstance(apps, list) else None,
        "volumes": len(volumes) if isinstance(volumes, list) else None,
        "billing": billing if isinstance(billing, (dict, list)) else None,
        "billingDetail": "" if billing is not None else billing_detail[-500:],
    }


def names(rows: Any) -> list[str]:
    if not isinstance(rows, list):
        return []
    result = []
    for row in rows:
        if isinstance(row, dict):
            value = row.get("Name") or row.get("name") or row.get("App Name") or row.get("app_name")
            if value:
                result.append(str(value))
    return result


def reset_account(account: Account) -> None:
    apps, _ = json_command(account, ["modal", "app", "list", "--json"])
    for name in names(apps):
        result = run(account, ["modal", "app", "stop", "-y", name])
        if result.returncode != 0 and "not found" not in (result.stderr or "").lower():
            raise RuntimeError(f"Could not stop app {name}: {(result.stderr or result.stdout)[-500:]}")
    volumes, _ = json_command(account, ["modal", "volume", "list", "--json"])
    for name in names(volumes):
        result = run(account, ["modal", "volume", "delete", "--allow-missing", "-y", name])
        if result.returncode != 0:
            raise RuntimeError(f"Could not delete volume {name}: {(result.stderr or result.stdout)[-500:]}")
    dicts, _ = json_command(account, ["modal", "dict", "list", "--json"])
    for name in names(dicts):
        result = run(account, ["modal", "dict", "delete", "--allow-missing", "-y", name])
        if result.returncode != 0:
            raise RuntimeError(f"Could not delete dict {name}: {(result.stderr or result.stdout)[-500:]}")


def ecosystem_config(ecosystem_id: str) -> dict[str, Any]:
    payload = json.loads((ROOT / "config/modal-worker-ecosystems.json").read_text(encoding="utf-8"))
    for item in payload.get("ecosystems", []):
        if item.get("id") == ecosystem_id:
            return item
    raise SystemExit(f"Unknown ecosystem: {ecosystem_id}")


def deploy(account: Account, ecosystem_id: str, worker_id: str) -> dict[str, Any]:
    ecosystem = ecosystem_config(ecosystem_id)
    extra = {
        "SAGA_MODAL_WORKER_ID": worker_id,
        "SAGA_MODAL_WORKER_STATE_DICT": ecosystem["stateDict"],
        "SAGA_MODAL_WORKER_VOLUME": ecosystem["volume"],
    }
    for entrypoint in (ecosystem["runtimeEntrypoint"], ecosystem["gatewayEntrypoint"]):
        result = run(account, ["modal", "deploy", entrypoint], extra=extra)
        if result.returncode != 0:
            raise RuntimeError(f"Deploy failed for {entrypoint}: {(result.stderr or result.stdout)[-1200:]}")
    prefetch = "prefetch_klein" if ecosystem_id == "flux2-klein-9b" else "prefetch_ltx25"
    code = (
        "import modal, json; "
        f"fn=modal.Function.from_name({ecosystem['runtimeApp']!r}, {prefetch!r}); "
        "result=fn.remote(False); print(json.dumps({'ready': bool(result.get('ready')), 'model': result.get('model')}))"
    )
    result = run(account, [sys.executable, "-c", code], extra=extra)
    if result.returncode != 0:
        raise RuntimeError(f"Prefetch failed: {(result.stderr or result.stdout)[-1200:]}")
    url_code = (
        "import modal; "
        f"fn=modal.Function.from_name({ecosystem['gatewayApp']!r}, {ecosystem['gatewayFunction']!r}); "
        "print(fn.get_web_url())"
    )
    url_result = run(account, [sys.executable, "-c", url_code], extra=extra)
    if url_result.returncode != 0:
        raise RuntimeError(f"Could not resolve gateway URL: {(url_result.stderr or url_result.stdout)[-800:]}")
    return {"gatewayUrl": (url_result.stdout or "").strip().splitlines()[-1], "ecosystem": ecosystem_id, "workerId": worker_id, "account": account.label}


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    inventory = sub.add_parser("inventory")
    inventory.add_argument("--out", default="modal-worker-inventory.json")
    reset = sub.add_parser("reset")
    reset.add_argument("account")
    deploy_cmd = sub.add_parser("deploy")
    deploy_cmd.add_argument("account")
    deploy_cmd.add_argument("ecosystem")
    deploy_cmd.add_argument("worker_id")
    args = parser.parse_args()
    accounts = load_accounts()
    by_label = {account.label: account for account in accounts}
    if args.command == "inventory":
        rows = [inventory_account(account) for account in accounts]
        Path(args.out).write_text(json.dumps({"count": len(rows), "accounts": rows}, indent=2), encoding="utf-8")
        print(json.dumps({"count": len(rows), "available": sum(row.get('state') == 'available' for row in rows), "disabled": sum(row.get('state') == 'disabled' for row in rows), "credit_exhausted": sum(row.get('state') == 'credit_exhausted' for row in rows)}))
        return
    account = by_label.get(args.account)
    if not account:
        raise SystemExit(f"Account not found in roster: {args.account}")
    if args.command == "reset":
        reset_account(account)
        print(json.dumps({"account": account.label, "reset": True}))
        return
    if args.command == "deploy":
        print(json.dumps(deploy(account, args.ecosystem, args.worker_id)))

if __name__ == "__main__":
    main()
'''
write("scripts/modal_worker_fleet.py", FLEET)

# Non-destructive inventory runs automatically after this platform patch. Provisioning is a separate explicit-config commit.
INVENTORY_WORKFLOW = r'''name: Modal Worker Fleet Inventory

on:
  push:
    branches: [studio/video-gallery-ux]
    paths:
      - "scripts/modal_worker_fleet.py"
      - "config/modal-worker-ecosystems.json"
      - ".github/workflows/modal-worker-inventory.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  inventory:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SAGA_MODAL_TOKENS_JSON: ${{ secrets.SAGA_MODAL_TOKENS_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install current Modal CLI with billing support
        run: python -m pip install --upgrade "modal>=1.5.1,<2"
      - name: Inventory all Modal accounts
        run: python scripts/modal_worker_fleet.py inventory --out modal-worker-inventory.json
      - name: Upload sanitized inventory
        uses: actions/upload-artifact@v4
        with:
          name: modal-worker-inventory-${{ github.run_id }}
          path: modal-worker-inventory.json
          retention-days: 7
'''
write(".github/workflows/modal-worker-inventory.yml", INVENTORY_WORKFLOW)

print("Worker fleet platform patch applied.")
